package com.perqa.byebox.ui.main

object Loc {
    private val ru = mapOf(
        "title_main" to "Главная",
        "title_proxies" to "Прокси",
        "title_settings" to "Настройки",
        "title_logs" to "Логи",
        "status_connected" to "VPN защищает трафик",
        "status_connecting" to "Поднимаем VPN-туннель",
        "status_reconnecting" to "Связь потеряна, переподключаемся",
        "status_disconnected" to "VPN отключен",
        "status_no_server" to "Сервер не выбран",
        "download" to "Скачивание",
        "upload" to "Загрузка",
        "quick_best" to "Лучший",
        "quick_share" to "Поделиться",
        "quick_vpn_settings" to "VPN Android",
        "quick_tile" to "Плитка",
        "no_active_config" to "Нет выбранной рабочей конфигурации",
        "conn_params" to "VPN параметры, DNS сервера, TUN стек, локальный прокси",
        "rules_params" to "Маршрутизация, профиль приложений, функции ядра Xray",
        "appearance_params" to "Тема оформления, степень отклика, стиль скруглений, анимация",
        "system_params" to "Логирование, автозапуск, проверка серверов, сброс настроек",
        "submenu_connection" to "Соединение",
        "submenu_rules" to "Правила",
        "submenu_appearance" to "Внешний вид",
        "submenu_system" to "Система",
        "back" to "Назад",
        "language" to "Язык",
        "lang_system" to "Системный (по умолчанию)",
        "lang_ru" to "Русский",
        "lang_en" to "English",
        "lang_zh" to "简体中文",
        "theme" to "Тема оформления",
        "tap_impact" to "Степень отклика",
        "tap_impact_none" to "Без сжатия (1.00)",
        "tap_impact_light" to "Легкий отклик (0.95)",
        "tap_impact_medium" to "Средний (0.90)",
        "tap_impact_deep" to "Глубокий отклик (0.85)",
        "tap_impact_sub" to "Физическое сжатие интерфейса при нажатии",
        "corner_roundness" to "Стиль скруглений",
        "corner_std" to "Стандартный (M3)",
        "corner_expr" to "Выразительный (M3 Expressive)",
        "corner_std_sub" to "Стандартный строгий дизайн Material Design",
        "corner_expr_sub" to "Крупные скругления углов и выразительная форма элементов",
        "effects_anim" to "Эффекты и анимация",
        "pulse_btn" to "Пульсация кнопки",
        "pulse_btn_sub" to "Анимированная пульсация центральной кнопки при активном подключении",
        "glass_bar" to "Стеклянный эффект",
        "glass_bar_sub" to "Эффект полупрозрачности (Glassmorphism) для нижней панели вкладок",
        "max_blur" to "Максимальное размытие",
        "max_blur_sub" to "Плотный матовый эффект без обводки (стиль Android 17, по умолчанию включен)",
        "logging" to "Логирование",
        "log_debug_desc" to "Все события, включая детали подключений",
        "log_info_desc" to "Основные события и изменения состояния",
        "log_warn_desc" to "Только предупреждения и ошибки",
        "log_err_desc" to "Только критические ошибки",
        "sys_settings" to "Системные настройки",
        "start_on_boot" to "Автозапуск при старте",
        "start_on_boot_sub" to "Автоматически поднимать VPN после перезагрузки устройства",
        "confirm_remove" to "Подтверждение удаления",
        "confirm_remove_sub" to "Спрашивать подтверждение перед удалением сервера из списка",
        "check_servers" to "Проверка серверов",
        "check_resource" to "Проверка ресурса",
        "resource_ok" to "Ресурс доступен",
        "resource_fail" to "Ресурс недоступен",
        "import_config" to "Добавить конфигурацию",
        "import_link" to "Ссылка",
        "import_qr" to "QR-код",
        "import_clipboard" to "Буфер обмена",
        "clipboard_empty" to "Буфер обмена пуст!",
        "clipboard_chip" to "Из буфера",
        "clear" to "Очистить",
        "unknown_format" to "Неизвестный формат",
        "direct_link" to "Прямая ссылка на сервер",
        "sub_link" to "Ссылка на подписку",
        "config_url_label" to "Ссылка или URL подписки",
        
        // Connections & Routing Details
        "ipv6_tunnel" to "IPv6 в туннеле",
        "ipv6_tunnel_sub" to "Включить IPv6-маршрутизацию в виртуальном интерфейсе",
        "prefer_ipv6" to "Предпочитать IPv6",
        "prefer_ipv6_sub" to "Запрашивать IPv6-адреса (AAAA) при резолве доменов",
        "lan_bypass" to "Обход локальных сетей",
        "lan_bypass_sub" to "LAN, loopback и link-local сети не попадают в VPN",
        "blocking_vpn" to "Блокировка трафика без VPN",
        "blocking_vpn_sub" to "Kill Switch — блокировать интернет-соединение, если VPN отключен или разорван",
        "dns_servers" to "DNS Сервера",
        "local_proxy" to "Локальный прокси",
        "vpn_mode" to "Режим VPN",
        "vpn_mode_sub" to "VPN перехватывает весь трафик устройства, иначе работает локальный прокси",
        "lan_sharing" to "Доступ из LAN",
        "lan_sharing_sub" to "Разрешить устройствам в локальной сети использовать ваш прокси",
        "socks_port_title" to "Локальный SOCKS порт",
        "socks_port_desc" to "Порт для подключения локальных клиентов к SOCKS5 прокси",
        "tun_stack_title" to "TUN Стек",
        "routing_rules" to "Правила маршрутизации",
        "routing_bypass_desc" to "Локальные сети и популярные региональные диапазоны идут напрямую",
        "routing_proxy_all_desc" to "Весь трафик устройства проходит через выбранный узел",
        "routing_direct_desc" to "Туннель не забирает трафик, удобно для диагностики",
        "custom_rules" to "Собственные правила",
        "custom_direct_title" to "Прямое подключение (DIRECT)",
        "custom_direct_desc" to "Домены или IP-адреса, которые должны подключаться напрямую без прокси (по одному в строке или через запятую)",
        "custom_proxy_title" to "Через VPN (PROXY)",
        "custom_proxy_desc" to "Домены или IP-адреса, которые должны принудительно направляться через VPN (по одному в строке или через запятую)",
        "app_profile" to "Профиль приложений",
        "selected_apps" to "Выбранные приложения",
        "select_btn" to "Выбрать",
        "xray_features" to "Функции ядра Xray",
        "sniffing" to "Сниффинг трафика",
        "sniffing_desc" to "Сниффить HTTP/TLS запросы для извлечения доменного имени",
        "fragment" to "Фрагментация (Fragment)",
        "fragment_desc" to "Тонкая разбивка TLS рукопожатия на пакеты для обхода систем активного блокирования DPI (ТСПУ)",
        "mux" to "Мультиплексирование (Mux)",
        "mux_desc" to "Mux — мультиплексирование TCP соединений для уменьшения задержки рукопожатия и экономии ресурсов батареи",
        "fake_dns" to "Fake DNS",
        "fake_dns_desc" to "Перехватывать DNS запросы и возвращать виртуальные IP адреса для более эффективной маршрутизации",
        "theme_title" to "Тема оформления",
        "haptics_title" to "Степень отклика",
        "roundness_title" to "Стиль скруглений",
        "effects_title" to "Эффекты и анимация",
        "dark_theme_style_title" to "Стиль темной темы",
        "display_params_title" to "Параметры отображения",
        "compact_proxy_list" to "Компактный список прокси",
        "compact_proxy_list_sub" to "Уменьшить размер элементов списка для экономии места",
        "show_flags" to "Показывать флаги стран",
        "show_flags_sub" to "Отображать флаги-эмодзи у каждого сервера",

        // Delete confirmation dialogs
        "delete_profile_confirm_title" to "Удалить профиль?",
        "delete_profile_confirm_msg" to "Профиль «{name}» будет удалён навсегда. Это действие нельзя отменить.",
        "delete_config_confirm_title" to "Удалить конфигурацию?",
        "delete_config_confirm_msg" to "Сервер «{name}» будет удалён из списка. Это действие нельзя отменить.",
        "delete_source_confirm_title" to "Удалить подписку?",
        "delete_source_confirm_msg" to "Подписка «{name}» и все её серверы будут удалены навсегда.",
        "delete_btn" to "Удалить",
        "cancel_btn" to "Отмена",

        // Routing — domain strategy
        "routing_domain_strategy" to "Стратегия доменов (Domain Strategy)",
        "routing_domain_strategy_desc" to "Определяет порядок разрешения IP при маршрутизации доменных имён",
        "domain_strategy_as_is" to "AsIs — не резолвить",
        "domain_strategy_as_is_desc" to "Передавать доменное имя напрямую, без DNS-резолва (по умолчанию)",
        "domain_strategy_ip_on_demand" to "IPOnDemand — резолвить всегда",
        "domain_strategy_ip_on_demand_desc" to "Резолвить доменное имя в IP при каждом совпадении правила",
        "domain_strategy_ip_if_non_match" to "IPIfNonMatch — резолвить при несовпадении",
        "domain_strategy_ip_if_non_match_desc" to "Резолвить в IP, если ни одно доменное правило не совпало",

        // Outbound domain resolve method
        "outbound_domain_resolve_method" to "Метод разрешения Outbound",
        "outbound_domain_resolve_method_desc" to "Способ разрешения доменных имён на стороне исходящего соединения",
        "outbound_resolve_default" to "Resolve — базовый резолв",
        "outbound_resolve_default_desc" to "Стандартное DNS-разрешение для исходящих соединений (по умолчанию)",
        "outbound_resolve_use_ip" to "UseIP — подставить IP",
        "outbound_resolve_use_ip_desc" to "Заменить доменное имя на IP-адрес перед передачей исходящему",
        "outbound_resolve_replace" to "UseIPv4 / UseIPv6 — резолвить и заменить",
        "outbound_resolve_replace_desc" to "Резолвить и заменять доменные имена на IP перед передачей",

        // Logs
        "logs_params" to "Журнал событий, дебаг-вывод, экспорт логов",
        "search_logs" to "Поиск в логах...",
        "logs_export" to "Экспорт",
        "logs_clear" to "Очистить",
        "logs_empty" to "Записей не найдено."
    )

    private val en = mapOf(
        "title_main" to "Main",
        "title_proxies" to "Proxies",
        "title_settings" to "Settings",
        "title_logs" to "Logs",
        "status_connected" to "VPN is protecting traffic",
        "status_connecting" to "Establishing VPN tunnel",
        "status_reconnecting" to "Connection lost, reconnecting",
        "status_disconnected" to "VPN disconnected",
        "status_no_server" to "No server selected",
        "download" to "Download",
        "upload" to "Upload",
        "quick_best" to "Best Server",
        "quick_share" to "Share Config",
        "quick_vpn_settings" to "VPN Android",
        "quick_tile" to "Add Tile",
        "no_active_config" to "No working configuration selected",
        "conn_params" to "VPN settings, DNS servers, TUN stack, local proxy",
        "rules_params" to "Routing, app routing, Xray core features",
        "appearance_params" to "Theme, click haptics, corner roundness, animations",
        "system_params" to "Logging, auto start, health check, reset",
        "submenu_connection" to "Connection",
        "submenu_rules" to "Rules",
        "submenu_appearance" to "Appearance",
        "submenu_system" to "System",
        "back" to "Back",
        "language" to "Language",
        "lang_system" to "System Default",
        "lang_ru" to "Русский",
        "lang_en" to "English",
        "lang_zh" to "简体中文",
        "theme" to "Theme",
        "tap_impact" to "Click Haptics",
        "tap_impact_none" to "No Haptics (1.00)",
        "tap_impact_light" to "Light (0.95)",
        "tap_impact_medium" to "Medium (0.90)",
        "tap_impact_deep" to "Deep (0.85)",
        "tap_impact_sub" to "UI scale squeeze on press",
        "corner_roundness" to "Corner Style",
        "corner_std" to "Standard (M3)",
        "corner_expr" to "Expressive (M3 Expressive)",
        "corner_std_sub" to "Standard strict Material Design",
        "corner_expr_sub" to "Larger corner radiuses and expressive shapes",
        "effects_anim" to "Effects & Animations",
        "pulse_btn" to "Pulse Button",
        "pulse_btn_sub" to "Pulse animation on central button when connected",
        "glass_bar" to "Glassmorphism",
        "glass_bar_sub" to "Translucent glass effect for bottom tab bar",
        "max_blur" to "Maximum Blur",
        "max_blur_sub" to "Dense matte background without outline (Android 17 style)",
        "logging" to "Logging",
        "log_debug_desc" to "All events, including connection details",
        "log_info_desc" to "Major events and state changes",
        "log_warn_desc" to "Warnings and errors only",
        "log_err_desc" to "Critical errors only",
        "sys_settings" to "System Settings",
        "start_on_boot" to "Start on Boot",
        "start_on_boot_sub" to "Automatically start VPN on device boot",
        "confirm_remove" to "Confirm Delete",
        "confirm_remove_sub" to "Show confirmation before deleting a server",
        "check_servers" to "Health Check",
        "check_resource" to "Test Resource",
        "resource_ok" to "Resource is reachable",
        "resource_fail" to "Resource is unreachable",
        "import_config" to "Add Configuration",
        "import_link" to "Link",
        "import_qr" to "QR Code",
        "import_clipboard" to "Clipboard",
        "clipboard_empty" to "Clipboard is empty!",
        "clipboard_chip" to "From clipboard",
        "clear" to "Clear",
        "unknown_format" to "Unknown format",
        "direct_link" to "Direct link to server",
        "sub_link" to "Subscription link",
        "config_url_label" to "Link or subscription URL",

        // Connections & Routing Details
        "ipv6_tunnel" to "IPv6 in Tunnel",
        "ipv6_tunnel_sub" to "Enable IPv6 routing in virtual interface",
        "prefer_ipv6" to "Prefer IPv6",
        "prefer_ipv6_sub" to "Request IPv6 addresses (AAAA) during domain resolution",
        "lan_bypass" to "Bypass Local Networks",
        "lan_bypass_sub" to "LAN, loopback, and link-local networks bypass VPN",
        "blocking_vpn" to "Block Traffic Without VPN",
        "blocking_vpn_sub" to "Kill Switch — block internet connection if VPN is disconnected or interrupted",
        "dns_servers" to "DNS Servers",
        "local_proxy" to "Local Proxy",
        "vpn_mode" to "VPN Mode",
        "vpn_mode_sub" to "VPN intercepts all device traffic, otherwise local proxy runs",
        "lan_sharing" to "Access from LAN",
        "lan_sharing_sub" to "Allow devices in local network to use your proxy",
        "socks_port_title" to "Local SOCKS Port",
        "socks_port_desc" to "Port for connecting local clients to SOCKS5 proxy",
        "tun_stack_title" to "TUN Stack",
        "routing_rules" to "Routing Rules",
        "routing_bypass_desc" to "Local networks and popular regional ranges go directly",
        "routing_proxy_all_desc" to "All device traffic passes through the selected node",
        "routing_direct_desc" to "Tunnel does not capture traffic, useful for diagnostics",
        "custom_rules" to "Custom Rules",
        "custom_direct_title" to "Direct Connection (DIRECT)",
        "custom_direct_desc" to "Domains or IP addresses that should connect directly without proxy (one per line or comma-separated)",
        "custom_proxy_title" to "Via VPN (PROXY)",
        "custom_proxy_desc" to "Domains or IP addresses that should be forced through the VPN (one per line or comma-separated)",
        "app_profile" to "App Profile",
        "selected_apps" to "Selected Apps",
        "select_btn" to "Select",
        "xray_features" to "Xray Core Features",
        "sniffing" to "Traffic Sniffing",
        "sniffing_desc" to "Sniff HTTP/TLS requests to extract domain name",
        "fragment" to "Fragmentation (Fragment)",
        "fragment_desc" to "Fine fragmenting of TLS handshake to bypass active DPI blocking systems",
        "mux" to "Multiplexing (Mux)",
        "mux_desc" to "Mux — TCP multiplexing to reduce handshake latency and save battery",
        "fake_dns" to "Fake DNS",
        "fake_dns_desc" to "Intercept DNS requests and return virtual IPs for more efficient routing",
        "theme_title" to "Theme",
        "haptics_title" to "Click Haptics",
        "roundness_title" to "Corner Style",
        "effects_title" to "Effects & Animations",
        "dark_theme_style_title" to "Dark Theme Style",
        "display_params_title" to "Display Options",
        "compact_proxy_list" to "Compact proxy list",
        "compact_proxy_list_sub" to "Reduce list item size to save space",
        "show_flags" to "Show country flags",
        "show_flags_sub" to "Display emoji flags for each server",

        // Delete confirmation dialogs
        "delete_profile_confirm_title" to "Delete Profile?",
        "delete_profile_confirm_msg" to "Profile \"{name}\" will be permanently deleted. This action cannot be undone.",
        "delete_config_confirm_title" to "Delete Configuration?",
        "delete_config_confirm_msg" to "Server \"{name}\" will be removed from the list. This action cannot be undone.",
        "delete_source_confirm_title" to "Delete Subscription?",
        "delete_source_confirm_msg" to "Subscription \"{name}\" and all its servers will be permanently deleted.",
        "delete_btn" to "Delete",
        "cancel_btn" to "Cancel",

        // Routing — domain strategy
        "routing_domain_strategy" to "Domain Strategy",
        "routing_domain_strategy_desc" to "Determines how domain names are resolved during routing",
        "domain_strategy_as_is" to "AsIs — no resolve",
        "domain_strategy_as_is_desc" to "Pass domain names directly without DNS resolution (default)",
        "domain_strategy_ip_on_demand" to "IPOnDemand — always resolve",
        "domain_strategy_ip_on_demand_desc" to "Resolve domain to IP on every rule match",
        "domain_strategy_ip_if_non_match" to "IPIfNonMatch — resolve on mismatch",
        "domain_strategy_ip_if_non_match_desc" to "Resolve to IP only if no domain rule matched",

        // Outbound domain resolve method
        "outbound_domain_resolve_method" to "Outbound Resolve Method",
        "outbound_domain_resolve_method_desc" to "How domain names are resolved on the outbound side",
        "outbound_resolve_default" to "Resolve — standard resolution",
        "outbound_resolve_default_desc" to "Standard DNS resolution for outbound connections (default)",
        "outbound_resolve_use_ip" to "UseIP — substitute IP",
        "outbound_resolve_use_ip_desc" to "Replace domain name with its IP address before sending to outbound",
        "outbound_resolve_replace" to "UseIPv4 / UseIPv6 — resolve and replace",
        "outbound_resolve_replace_desc" to "Resolve and replace domain names with IP addresses before outbound",

        // Logs
        "logs_params" to "Event journal, debug output, log export",
        "search_logs" to "Search logs...",
        "logs_export" to "Export",
        "logs_clear" to "Clear",
        "logs_empty" to "No records found."
    )

    private val zh = mapOf(
        "title_main" to "主页",
        "title_proxies" to "代理",
        "title_settings" to "设置",
        "title_logs" to "日志",
        "status_connected" to "VPN 正在保护流量",
        "status_connecting" to "正在建立 VPN 隧道",
        "status_reconnecting" to "连接已断开，正在重新连接",
        "status_disconnected" to "VPN 已断开",
        "status_no_server" to "未选择服务器",
        "download" to "下载",
        "upload" to "上传",
        "quick_best" to "最佳服务器",
        "quick_share" to "分享配置",
        "quick_vpn_settings" to "系统 VPN",
        "quick_tile" to "添加瓷贴",
        "no_active_config" to "未选择有效的配置",
        "conn_params" to "VPN 参数、DNS 服务器、TUN 栈、本地代理",
        "rules_params" to "路由、应用代理、Xray 内核功能",
        "appearance_params" to "主题风格、触觉反馈、圆角样式、动画",
        "system_params" to "日志记录、开机自启、服务器检查、重置设置",
        "submenu_connection" to "连接",
        "submenu_rules" to "规则",
        "submenu_appearance" to "外观",
        "submenu_system" to "系统",
        "back" to "返回",
        "language" to "语言",
        "lang_system" to "系统默认",
        "lang_ru" to "Русский",
        "lang_en" to "English",
        "lang_zh" to "简体中文",
        "theme" to "主题",
        "tap_impact" to "按压触觉反馈",
        "tap_impact_none" to "无缩放 (1.00)",
        "tap_impact_light" to "轻微 (0.95)",
        "tap_impact_medium" to "中等 (0.90)",
        "tap_impact_deep" to "强烈 (0.85)",
        "tap_impact_sub" to "按压时界面物理缩放挤压效果",
        "corner_roundness" to "圆角风格",
        "corner_std" to "标准 (M3)",
        "corner_expr" to "丰富 (M3 Expressive)",
        "corner_std_sub" to "标准的 Material Design 严谨设计",
        "corner_expr_sub" to "更大的圆角和更具表现力的形状",
        "effects_anim" to "特效与动画",
        "pulse_btn" to "按钮呼吸灯",
        "pulse_btn_sub" to "连接成功时中心按钮的呼吸动画效果",
        "glass_bar" to "毛玻璃效果",
        "glass_bar_sub" to "底部导航栏的半透明毛玻璃效果",
        "max_blur" to "最大模糊",
        "max_blur_sub" to "无描边的紧密磨砂效果（Android 17 风格，默认开启）",
        "logging" to "日志记录",
        "log_debug_desc" to "所有事件，包括连接 the 详细信息",
        "log_info_desc" to "主要事件和状态更改",
        "log_warn_desc" to "仅限警告和错误",
        "log_err_desc" to "仅限严重错误",
        "sys_settings" to "系统设置",
        "start_on_boot" to "开机自启",
        "start_on_boot_sub" to "设备开机后自动启动 VPN 连接",
        "confirm_remove" to "删除确认",
        "confirm_remove_sub" to "从列表中删除服务器前询问确认",
        "check_servers" to "服务器连接性检查",
        "check_resource" to "测试资源地址",
        "resource_ok" to "测试成功，资源可达",
        "resource_fail" to "测试失败，资源不可达",
        "import_config" to "添加配置",
        "import_link" to "链接导入",
        "import_qr" to "扫码导入",
        "import_clipboard" to "从剪贴板导入",
        "clipboard_empty" to "剪贴板为空！",
        "clipboard_chip" to "剪贴板",
        "clear" to "清除",
        "unknown_format" to "未知格式",
        "direct_link" to "服务器直连配置链接",
        "sub_link" to "订阅链接",
        "config_url_label" to "链接或订阅 URL",

        // Connections & Routing Details
        "ipv6_tunnel" to "隧道中的 IPv6",
        "ipv6_tunnel_sub" to "在虚拟接口中启用 IPv6 路由",
        "prefer_ipv6" to "首选 IPv6",
        "prefer_ipv6_sub" to "在域名解析期间请求 IPv6 地址 (AAAA)",
        "lan_bypass" to "绕过局域网",
        "lan_bypass_sub" to "局域网、环回和链路本地网络不进入 VPN",
        "blocking_vpn" to "无 VPN 时拦截流量",
        "blocking_vpn_sub" to "Kill Switch — 如果 VPN 断开或中断，则阻止互联网连接",
        "dns_servers" to "DNS 服务器",
        "local_proxy" to "本地代理",
        "vpn_mode" to "VPN 模式",
        "vpn_mode_sub" to "VPN 拦截所有设备流量，否则运行本地代理",
        "lan_sharing" to "允许局域网连接",
        "lan_sharing_sub" to "允许局域网中的其他设备使用您的代理",
        "socks_port_title" to "本地 SOCKS 端口",
        "socks_port_desc" to "连接本地客户端到 SOCKS5 代理的端口",
        "tun_stack_title" to "TUN 堆栈",
        "routing_rules" to "路由规则",
        "routing_bypass_desc" to "本地网络和常用区域 IP 直连",
        "routing_proxy_all_desc" to "设备的所有流量均通过所选节点",
        "routing_direct_desc" to "隧道不获取流量，便于诊断",
        "custom_rules" to "自定义规则",
        "custom_direct_title" to "直连规则 (DIRECT)",
        "custom_direct_desc" to "应直接连接而不通过代理的域名或 IP 地址（每行一个或用逗号分隔）",
        "custom_proxy_title" to "代理规则 (PROXY)",
        "custom_proxy_desc" to "应强制通过 VPN 的域名或 IP 地址（每行一个或用逗号分隔）",
        "app_profile" to "应用代理解析",
        "selected_apps" to "已选应用",
        "select_btn" to "选择",
        "xray_features" to "Xray 内核功能",
        "sniffing" to "流量嗅探",
        "sniffing_desc" to "嗅探 HTTP/TLS 请求以提取域名",
        "fragment" to "分片功能 (Fragment)",
        "fragment_desc" to "微调 TLS 握手分片以绕过 DPI 主动阻断系统",
        "mux" to "多路复用 (Mux)",
        "mux_desc" to "Mux — TCP 多路复用以减少握手延迟并节省电量",
        "fake_dns" to "Fake DNS",
        "fake_dns_desc" to "拦截 DNS 请求并返回虚拟 IP 以进行更高效的路由",
        "theme_title" to "主题",
        "haptics_title" to "触觉反馈",
        "roundness_title" to "圆角样式",
        "effects_title" to "特效与动画",
        "dark_theme_style_title" to "深色主题样式",
        "display_params_title" to "显示选项",
        "compact_proxy_list" to "紧凑代理列表",
        "compact_proxy_list_sub" to "缩小列表项尺寸以节省空间",
        "show_flags" to "显示国旗",
        "show_flags_sub" to "为每个服务器显示国旗",

        // Delete confirmation dialogs
        "delete_profile_confirm_title" to "删除配置文件？",
        "delete_profile_confirm_msg" to "配置文件「{name}」将被永久删除，此操作无法撤销。",
        "delete_config_confirm_title" to "删除配置？",
        "delete_config_confirm_msg" to "服务器「{name}」将从列表中移除，此操作无法撤销。",
        "delete_source_confirm_title" to "删除订阅？",
        "delete_source_confirm_msg" to "订阅「{name}」及其所有服务器将被永久删除。",
        "delete_btn" to "删除",
        "cancel_btn" to "取消",

        // Routing — domain strategy
        "routing_domain_strategy" to "域名策略 (Domain Strategy)",
        "routing_domain_strategy_desc" to "决定路由时如何解析域名",
        "domain_strategy_as_is" to "AsIs — 不解析",
        "domain_strategy_as_is_desc" to "直接传递域名，不进行 DNS 解析（默认）",
        "domain_strategy_ip_on_demand" to "IPOnDemand — 始终解析",
        "domain_strategy_ip_on_demand_desc" to "每次规则匹配时将域名解析为 IP",
        "domain_strategy_ip_if_non_match" to "IPIfNonMatch — 无匹配时解析",
        "domain_strategy_ip_if_non_match_desc" to "仅在没有域名规则匹配时解析为 IP",

        // Outbound domain resolve method
        "outbound_domain_resolve_method" to "出站解析方式",
        "outbound_domain_resolve_method_desc" to "出站连接侧域名的解析方式",
        "outbound_resolve_default" to "Resolve — 标准解析",
        "outbound_resolve_default_desc" to "出站连接的标准 DNS 解析（默认）",
        "outbound_resolve_use_ip" to "UseIP — 替换为 IP",
        "outbound_resolve_use_ip_desc" to "发送到出站之前将域名替换为 IP 地址",
        "outbound_resolve_replace" to "UseIPv4 / UseIPv6 — 解析并替换",
        "outbound_resolve_replace_desc" to "解析并将域名替换为 IP 后发送至出站",

        // Logs
        "logs_params" to "事件日志、调试输出、日志导出",
        "search_logs" to "搜索日志...",
        "logs_export" to "导出",
        "logs_clear" to "清除",
        "logs_empty" to "未找到记录。"
    )

    fun get(key: String, lang: String): String {
        val resolvedLang = if (lang == "system") {
            val sysLang = java.util.Locale.getDefault().language
            when {
                sysLang.startsWith("ru") || sysLang.startsWith("be") || sysLang.startsWith("uk") || sysLang.startsWith("kk") || sysLang.startsWith("ky") -> "ru"
                sysLang.startsWith("zh") -> "zh"
                else -> "en"
            }
        } else {
            lang
        }
        val dict = when (resolvedLang) {
            "en" -> en
            "zh" -> zh
            else -> ru
        }
        return dict[key] ?: ru[key] ?: key
    }
}
