package com.perqa.byebox.ui.main

object Loc {
    private val ru = mapOf(
        "title_main" to "Главная",
        "title_proxies" to "Прокси",
        "title_settings" to "Настройки",
        "title_logs" to "Логи",
        "status_connected" to "VPN защищает трафик",
        "status_connecting" to "Поднимаем VPN-туннель",
        "status_reconnecting" to "Связь потеряна, переподключаемся",
        "status_disconnected" to "VPN отключен",
        "status_no_server" to "Сервер не выбран",
        "download" to "Скачивание",
        "upload" to "Загрузка",
        "quick_best" to "Лучший",
        "quick_share" to "Поделиться",
        "quick_vpn_settings" to "VPN Android",
        "quick_tile" to "Плитка",
        "no_active_config" to "Нет выбранной рабочей конфигурации",
        "conn_params" to "VPN параметры, DNS сервера, TUN стек, локальный прокси",
        "rules_params" to "Маршрутизация, профиль приложений, функции ядра Xray",
        "appearance_params" to "Тема оформления, степень отклика, стиль скруглений, анимация",
        "system_params" to "Логирование, автозапуск, проверка серверов, сброс настроек",
        "submenu_connection" to "Соединение",
        "submenu_rules" to "Правила",
        "submenu_appearance" to "Внешний вид",
        "submenu_system" to "Система",
        "back" to "Назад",
        "language" to "Язык",
        "lang_system" to "Системный (по умолчанию)",
        "lang_ru" to "Русский",
        "lang_en" to "English",
        "lang_zh" to "简体中文",
        "theme" to "Тема оформления",
        "tap_impact" to "Степень отклика",
        "tap_impact_none" to "Без сжатия (1.00)",
        "tap_impact_light" to "Легкий отклик (0.95)",
        "tap_impact_medium" to "Средний (0.90)",
        "tap_impact_deep" to "Глубокий отклик (0.85)",
        "tap_impact_sub" to "Физическое сжатие интерфейса при нажатии",
        "corner_roundness" to "Стиль скруглений",
        "corner_std" to "Стандартный (M3)",
        "corner_expr" to "Выразительный (M3 Expressive)",
        "corner_std_sub" to "Стандартный строгий дизайн Material Design",
        "corner_expr_sub" to "Крупные скругления углов и выразительная форма элементов",
        "effects_anim" to "Эффекты и анимация",
        "pulse_btn" to "Пульсация кнопки",
        "pulse_btn_sub" to "Анимированная пульсация центральной кнопки при активном подключении",
        "glass_bar" to "Стеклянный эффект",
        "glass_bar_sub" to "Эффект полупрозрачности (Glassmorphism) для нижней панели вкладок",
        "max_blur" to "Максимальное размытие",
        "max_blur_sub" to "Плотный матовый эффект без обводки (стиль Android 17, по умолчанию включен)",
        "logging" to "Логирование",
        "log_debug_desc" to "Все события, включая детали подключений",
        "log_info_desc" to "Основные события и изменения состояния",
        "log_warn_desc" to "Только предупреждения и ошибки",
        "log_err_desc" to "Только критические ошибки",
        "sys_settings" to "Системные настройки",
        "start_on_boot" to "Автозапуск при старте",
        "start_on_boot_sub" to "Автоматически поднимать VPN после перезагрузки устройства",
        "confirm_remove" to "Подтверждение удаления",
        "confirm_remove_sub" to "Спрашивать подтверждение перед удалением сервера из списка",
        "check_servers" to "Проверка серверов",
        "check_resource" to "Проверка ресурса",
        "resource_ok" to "Ресурс доступен",
        "resource_fail" to "Ресурс недоступен",
        "import_config" to "Добавить конфигурацию",
        "import_link" to "Ссылка",
        "import_qr" to "QR-код",
        "import_clipboard" to "Буфер обмена",
        "clipboard_empty" to "Буфер обмена пуст!",
        "clipboard_chip" to "Из буфера",
        "clear" to "Очистить",
        "unknown_format" to "Неизвестный формат",
        "direct_link" to "Прямая ссылка на сервер",
        "sub_link" to "Ссылка на подписку",
        "config_url_label" to "Ссылка или URL подписки",
        
        // Connections & Routing Details
        "ipv6_tunnel" to "IPv6 в туннеле",
        "ipv6_tunnel_sub" to "Включить IPv6-маршрутизацию в виртуальном интерфейсе",
        "prefer_ipv6" to "Предпочитать IPv6",
        "prefer_ipv6_sub" to "Запрашивать IPv6-адреса (AAAA) при резолве доменов",
        "lan_bypass" to "Обход локальных сетей",
        "lan_bypass_sub" to "LAN, loopback и link-local сети не попадают в VPN",
        "blocking_vpn" to "Блокировка трафика без VPN",
        "blocking_vpn_sub" to "Kill Switch — блокировать интернет-соединение, если VPN отключен или разорван",
        "dns_servers" to "DNS Сервера",
        "local_proxy" to "Локальный прокси",
        "vpn_mode" to "Режим VPN",
        "vpn_mode_sub" to "VPN перехватывает весь трафик устройства, иначе работает локальный прокси",
        "lan_sharing" to "Доступ из LAN",
        "lan_sharing_sub" to "Разрешить устройствам в локальной сети использовать ваш прокси",
        "socks_port_title" to "Локальный SOCKS порт",
        "socks_port_desc" to "Порт для подключения локальных клиентов к SOCKS5 прокси",
        "tun_stack_title" to "TUN Стек",
        "routing_rules" to "Правила маршрутизации",
        "routing_bypass_desc" to "Локальные сети и популярные региональные диапазоны идут напрямую",
        "routing_proxy_all_desc" to "Весь трафик устройства проходит через выбранный узел",
        "routing_direct_desc" to "Туннель не забирает трафик, удобно для диагностики",
        "custom_rules" to "Собственные правила",
        "custom_direct_title" to "Прямое подключение (DIRECT)",
        "custom_direct_desc" to "Домены или IP-адреса, которые должны подключаться напрямую без прокси (по одному в строке или через запятую)",
        "custom_proxy_title" to "Через VPN (PROXY)",
        "custom_proxy_desc" to "Домены или IP-адреса, которые должны принудительно направляться через VPN (по одному в строке или через запятую)",
        "app_profile" to "Профиль приложений",
        "selected_apps" to "Выбранные приложения",
        "select_btn" to "Выбрать",
        "xray_features" to "Функции ядра Xray",
        "sniffing" to "Сниффинг трафика",
        "sniffing_desc" to "Сниффить HTTP/TLS запросы для извлечения доменного имени",
        "fragment" to "Фрагментация (Fragment)",
        "fragment_desc" to "Тонкая разбивка TLS рукопожатия на пакеты для обхода систем активного блокирования DPI (ТСПУ)",
        "mux" to "Мультиплексирование (Mux)",
        "mux_desc" to "Mux — мультиплексирование TCP соединений для уменьшения задержки рукопожатия и экономии ресурсов батареи",
        "fake_dns" to "Fake DNS",
        "fake_dns_desc" to "Перехватывать DNS запросы и возвращать виртуальные IP адреса для более эффективной маршрутизации",
        "theme_title" to "Тема оформления",
        "haptics_title" to "Степень отклика",
        "roundness_title" to "Стиль скруглений",
        "effects_title" to "Эффекты и анимация",
        "dark_theme_style_title" to "Стиль темной темы",
        "display_params_title" to "Параметры отображения",
        "compact_proxy_list" to "Компактный список прокси",
        "compact_proxy_list_sub" to "Уменьшить размер элементов списка для экономии места",
        "show_flags" to "Показывать флаги стран",
        "show_flags_sub" to "Отображать флаги-эмодзи у каждого сервера",

        // Delete confirmation dialogs
        "delete_profile_confirm_title" to "Удалить профиль?",
        "delete_profile_confirm_msg" to "Профиль «{name}» будет удалён навсегда. Это действие нельзя отменить.",
        "delete_config_confirm_title" to "Удалить конфигурацию?",
        "delete_config_confirm_msg" to "Сервер «{name}» будет удалён из списка. Это действие нельзя отменить.",
        "delete_source_confirm_title" to "Удалить подписку?",
        "delete_source_confirm_msg" to "Подписка «{name}» и все её серверы будут удалены навсегда.",
        "delete_btn" to "Удалить",
        "cancel_btn" to "Отмена",

        // Routing — domain strategy
        "routing_domain_strategy" to "Стратегия доменов (Domain Strategy)",
        "routing_domain_strategy_desc" to "Определяет порядок разрешения IP при маршрутизации доменных имён",
        "domain_strategy_as_is" to "AsIs — не резолвить",
        "domain_strategy_as_is_desc" to "Передавать доменное имя напрямую, без DNS-резолва (по умолчанию)",
        "domain_strategy_ip_on_demand" to "IPOnDemand — резолвить всегда",
        "domain_strategy_ip_on_demand_desc" to "Резолвить доменное имя в IP при каждом совпадении правила",
        "domain_strategy_ip_if_non_match" to "IPIfNonMatch — резолвить при несовпадении",
        "domain_strategy_ip_if_non_match_desc" to "Резолвить в IP, если ни одно доменное правило не совпало",

        // Outbound domain resolve method
        "outbound_domain_resolve_method" to "Метод разрешения Outbound",
        "outbound_domain_resolve_method_desc" to "Способ разрешения доменных имён на стороне исходящего соединения",
        "outbound_resolve_default" to "Resolve — базовый резолв",
        "outbound_resolve_default_desc" to "Стандартное DNS-разрешение для исходящих соединений (по умолчанию)",
        "outbound_resolve_use_ip" to "UseIP — подставить IP",
        "outbound_resolve_use_ip_desc" to "Заменить доменное имя на IP-адрес перед передачей исходящему",
        "outbound_resolve_replace" to "UseIPv4 / UseIPv6 — резолвить и заменить",
        "outbound_resolve_replace_desc" to "Резолвить и заменять доменные имена на IP перед передачей",

        // Logs
        "logs_params" to "Журнал событий, дебаг-вывод, экспорт логов",
        "search_logs" to "Поиск в логах...",
        "logs_export" to "Экспорт",
        "logs_clear" to "Очистить",
        "logs_empty" to "Записей не найдено.",

        // Dashboard
        "profile_presets" to "Профили настроек",
        "manage_profiles" to "Управление профилями",
        "quick_utilities" to "Быстрые утилиты",
        "btn_connected" to "ВКЛЮЧЕНО",
        "btn_connecting" to "ПОИСК...",
        "btn_reconnecting" to "ОТМЕНА",
        "btn_disconnected" to "СТАРТ",
        "default_profile" to "По умолчанию",
        "current_server" to "Текущий",
        "no_assigned_server" to "Не назначен (Текущий)",

        // Proxy tab
        "configurations" to "Конфигурации",
        "local_configs" to "Локальные конфигурации",
        "test_ping_all" to "Тест пинга всех",
        "refresh_subs" to "Обновить подписки",
        "search_nodes" to "Поиск узлов, стран, протоколов",
        "sort_nodes" to "Сортировка узлов",
        "no_configs" to "Нет конфигураций",
        "nothing_found" to "Ничего не найдено",
        "search_try_again" to "Попробуйте изменить запрос или сбросить фильтр.",
        "add_config_hint" to "Добавьте ссылку на конфиг или подписку выше.",
        "clear_search" to "Сбросить поиск",
        "expand" to "Раскрыть",
        "collapse" to "Скрыть",
        "import_placeholder" to "Вставьте vless://, vmess://, ss://, trojan://",
        "import_error_hint" to "Вставьте ссылку на конфиг или подписку",
        "ping" to "Пинг",
        "refresh" to "Обновить",
        "rename" to "Имя",
        "delete" to "Удалить",
        "save" to "Сохранить",
        "cancel" to "Отмена",
        "nodes_count" to "узл.",
        "source" to "Источник",
        "name" to "Имя",
        "settings" to "Настройки",
        "sort_by" to "Сортировка",
        "filter_by" to "Фильтр",
        "open_filters" to "Открыть фильтры",
        "sort_and_filters" to "Сортировка и фильтры",
        "refresh_short" to "Обн.",
        "add" to "Добавить",
        "quick_switch_profiles" to "Профили быстрого переключения",
        "new_profile" to "Новый профиль",
        "add_profile" to "Добавить профиль",
        "profile_sort_hint" to "Зажмите рукоятку для сортировки. Нажмите на плитку профиля, чтобы изменить его параметры.",
        "drag_handle" to "Перетащить",
        "active_label" to "АКТИВЕН",
        "edit" to "Редактировать",
        "exit" to "Выйти",
        "profile_settings" to "Настройки профиля",
        "basic_settings" to "ОСНОВНЫЕ НАСТРОЙКИ",
        "profile_name_label" to "Название профиля",
        "profile_name_hint" to "Укажите запоминающееся имя для этого набора настроек",
        "profile_label" to "Профиль",
        "dns_servers_title" to "DNS СЕРВЕРА",
        "inherit_dns" to "Наследовать от базовых настроек",
        "inherit_dns_sub" to "Глобальные настройки DNS из раздела настроек",
        "last_active_server" to "Предыдущий активный (автосохранение)",
        "dont_change_server" to "Не изменять (текущий сервер)",
        "use_current_server" to "Использовать текущий сервер",
        "assigned_server" to "Привязанный сервер",
        "assigned_server_hint" to "Выберите сервер для автоматического переключения при активации профиля.",
        "unsaved_changes_title" to "Несохраненные изменения",
        "unsaved_changes_msg" to "Несохраненные изменения будут потеряны. Вы действительно хотите выйти?",
        "vpn_connected" to "VPN подключен",
        "raising_tunnel" to "Поднимаем туннель",
        "reconnecting_msg" to "Идёт переподключение",
        "vpn_disconnected" to "VPN отключен",
        "press_to_enter_ip" to "Нажмите для ввода IP",
        "example_dns" to "Например: 8.8.4.4",
        "example_direct" to "Например: yandex.ru, 192.168.1.1",
        "example_proxy" to "Например: google.com, instagram.com",
        "qr_scan_hint" to "Наведите камеру на QR-код",
        "qr_camera_denied" to "Разрешение на камеру не выдано",
        "invalid_port" to "Некорректный порт (1..65535)",
        "empty_fields" to "Имя, адрес и пароль не могут быть пустыми",
        "link_copied" to "Ссылка скопирована!",
        "local_import" to "Локальный импорт",
        "edit_config" to "Редактирование",
        "close_btn" to "Закрыть",
        "done_btn" to "Готово",
        "change_btn" to "Изменить",
        "remark_label" to "Название (Remarks)",
        "address_label" to "Адрес (IP/Host)",
        "port_label" to "Порт",
        "security_label" to "Безопасность (security)",
        "transport_label" to "Транспорт (network)",
        "protocol_field" to "Протокол",
        "address_field" to "Адрес",
        "transport_field" to "Транспорт",
        "source_field" to "Источник",
        "discard_btn" to "Выйти",
        "stay_btn" to "Остаться",
        "sort_nodes" to "Сортировка узлов",
        "sort_by_fmt" to "Сортировка: %s",
        "filter_by_fmt" to "Фильтр: %s",
        "open_filters_cd" to "Открыть фильтры",
        "nodes_count_fmt" to "%d узл.",
        "save_cd" to "Сохранить",
        "expand_cd" to "Развернуть",
        "collapse_cd" to "Свернуть",
        "settings_cd" to "Настройки",
        "delete_cd" to "Удалить",
        "add_cd" to "Добавить профиль",
        "back_cd" to "Назад",
        "ping_cd" to "Пинг",
        "edit_cd" to "Редактировать",
        "sources_nodes_fmt" to "%d источника · %d узлов",
        "import_desc" to "Введите ссылку на прокси-сервер (vless, vmess, ss, trojan) или ссылку на подписку (http/https):",
        "expired" to "истекла",
        "today" to "сегодня",
        "until_date" to "до %s",
        "sort_default" to "По умолчанию",
        "sort_source" to "Источник",
        "sort_ping" to "Пинг",
        "sort_name" to "Имя",

        // Dark theme styles
        "dark_standard" to "Стандартный темный",
        "dark_standard_sub" to "Material Design по умолчанию",
        "dark_deep_slate" to "Мягкий серый",
        "dark_deep_slate_sub" to "Темно-угольный оттенок (#121212)",
        "dark_midnight_navy" to "Глубокий синий",
        "dark_midnight_navy_sub" to "Элегантный полночный оттенок (#080C14)",
        "dark_pure_black" to "OLED супер-черный",
        "dark_pure_black_sub" to "Чистый черный фон (#000000) для OLED",

        // DNS descriptions
        "dns_system_desc" to "Использовать системные DNS-адреса вашего Android-устройства",
        "dns_google_desc" to "Безопасные и быстрые DNS от Google (8.8.8.8, 8.8.4.4)",
        "dns_cloudflare_desc" to "Конфиденциальные DNS от Cloudflare (1.1.1.1, 1.0.0.1)",
        "dns_adguard_desc" to "Фильтрация рекламы, трекеров и фишинговых сайтов",
        "tun_stack_title" to "TUN СТЕК",
        "tun_inherit" to "Наследовать от базовых настроек",
        "tun_inherit_sub" to "Глобальный стек TUN из раздела настроек",
        "tun_gvisor_desc" to "Стек на базе gVisor (по умолчанию, высокая стабильность)",
        "tun_system_desc" to "Системный сетевой стек Android",
        "tun_mixed_desc" to "Смешанный сетевой стек для оптимизации маршрутизации",
        "xray_core_features" to "ФУНКЦИИ ЯДРА XRAY",
        "option_inherit" to "Наследовать",
        "option_enabled" to "Включено",
        "option_disabled" to "Выключено",
        "xray_sniffing" to "Сниффинг трафика",
        "xray_sniffing_desc" to "Автоматическое определение доменных имен для точной фильтрации и обхода блокировок.",
        "xray_fragment_desc" to "Разбиение пакетов для обхода глубокого анализа пакетов (DPI) провайдерами.",
        "xray_mux_desc" to "Объединение TCP-соединений в один канал для снижения задержек установления связи.",
        "xray_fake_dns_desc" to "Подмена реальных DNS-ответов фейковыми IP-адресами для ускорения резолва и повышения анонимности.",
        "routing_title" to "МАРШРУТИЗАЦИЯ ТРАФИКА",
        "routing_inherit" to "Наследовать от базовых настроек",
        "routing_inherit_sub" to "Глобальный профиль маршрутизации",
        "routing_bypass" to "Обход LAN, Китая и РФ",
        "routing_bypass_sub" to "Ресурсы локальной сети и региональные сайты (РФ, Китай) направляются напрямую, остальные — через прокси.",
        "routing_proxy_all" to "Проксировать всё",
        "routing_proxy_all_sub" to "Абсолютно весь трафик устройства направляется через VPN туннель.",
        "routing_direct" to "Прямое подключение",
        "routing_direct_sub" to "Все соединения идут напрямую в обход VPN проксирования.",
        "app_routing_title" to "ТУННЕЛИРОВАНИЕ ПРИЛОЖЕНИЙ",
        "app_routing_inherit" to "Наследовать от базовых настроек",
        "app_routing_inherit_sub" to "Глобальные настройки туннелирования приложений",
        "app_routing_all" to "Все приложения",
        "app_routing_all_sub" to "Проксировать трафик абсолютно всех установленных приложений.",
        "app_routing_selected" to "Только выбранные приложения",
        "app_routing_selected_sub" to "VPN туннелирование будет работать исключительно для выбранных в списке приложений.",
        "app_routing_bypass" to "Обход выбранных приложений",
        "app_routing_bypass_sub" to "Выбранные приложения будут работать напрямую в обход VPN, остальные — через прокси.",
        "app_routing_select_title" to "Выбранные приложения",
        "app_routing_select_sub" to "%d приложений выбрано",
        "app_routing_select_btn" to "Выбрать",
        "custom_rules_title" to "ПОЛЬЗОВАТЕЛЬСКИЕ ПРАВИЛА",
        "custom_rules_inherit_direct" to "Наследовать правила DIRECT",
        "custom_rules_inherit_direct_sub" to "Использовать глобальный список прямого подключения",
        "custom_rules_own_direct" to "Собственные правила DIRECT",
        "custom_rules_own_direct_sub" to "Задать индивидуальный список доменов и IP для прямого подключения",
        "custom_rules_inherit_proxy" to "Наследовать правила PROXY",
        "custom_rules_inherit_proxy_sub" to "Использовать глобальный список проксирования",
        "custom_rules_own_proxy" to "Собственные правила PROXY",
        "custom_rules_own_proxy_sub" to "Задать индивидуальный список доменов и IP для проксирования",
        "save_changes" to "Сохранить изменения",
        "select_server" to "Выбор сервера",
        "dont_change_server_picker" to "Не изменять (использовать текущий сервер)",
        "last_active_server_picker" to "Предыдущий активный (автосохранение)",

        // Config details sheet
        "config_details_editing" to "Редактирование",
        "config_details_close" to "Закрыть",
        "config_details_uuid" to "UUID / Пароль",
        "config_details_sni" to "SNI",
        "config_details_security" to "Безопасность (security)",
        "config_details_transport" to "Транспорт (network)",
        "config_details_protocol" to "Протокол",
        "config_details_address" to "Адрес",
        "config_details_transport_val" to "Транспорт",
        "config_details_security_val" to "Безопасность",
        "config_details_source" to "Источник",
        "config_details_cancel" to "Отмена",
        "config_details_save" to "Сохранить",
        "config_details_done" to "Готово",
        "config_details_change" to "Изменить",
        "config_details_unsaved_title" to "Несохраненные изменения",
        "config_details_unsaved_msg" to "У вас есть несохраненные изменения. Выйти без сохранения?",
        "config_details_exit" to "Выйти",
        "config_details_stay" to "Остаться",

        // App picker
        "app_picker_title" to "Выбор приложений",
        "app_picker_count" to "%d выбрано",
        "app_picker_found" to "Найдено: %d",
        "app_picker_hide_system" to "Скрыть системные",
        "app_picker_search" to "Поиск по имени или пакету...",
        "app_picker_clear" to "Очистить",
        "app_picker_save" to "Сохранить изменения",

        // Health check
        "health_url_label" to "URL ресурса",
        "health_check_cd" to "Проверить",

        // ViewModel toasts
        "toast_connection_failure" to "Сбой подключения",
        "toast_server_selected" to "Выбран сервер: %s",
        "toast_no_configs" to "Нет доступных конфигураций",
        "toast_best_server" to "Лучший сервер: %s",
        "toast_adding_subscription" to "Добавление подписки...",
        "toast_imported_servers" to "Импортировано серверов: %d",
        "toast_loaded_zero" to "Загружено 0 серверов",
        "toast_server_added" to "Сервер успешно добавлен!",
        "toast_invalid_link" to "Ошибка: Неподдерживаемый формат ссылки!",
        "toast_updating_subs" to "Обновление подписок...",
        "toast_updated_servers" to "Обновлено серверов: %d",
        "toast_source_not_found" to "Источник не найден",
        "toast_updating_sub" to "Обновление подписки...",
        "toast_source_renamed" to "Источник переименован",
        "toast_deleted_source" to "Удалено: %s",
        "toast_deleted_server" to "Удалено: %s",
        "toast_config_updated" to "Конфигурация обновлена",
        "update_latest" to "Установлена последняя версия",
        "update_available" to "Доступно обновление %s",
        "update_check" to "Проверить обновления",
        "update_check_fail" to "Не удалось проверить обновления",
        "update_current_version" to "Версия %s",
        "update_whats_new" to "Что нового",
        "update_hide" to "Скрыть",
        "update_download" to "Скачать обновление",
        "update_latest" to "Установлена последняя версия",
        "update_checking" to "Проверяем…",
        "settings_backup" to "Резервная копия",
        "settings_export" to "Экспорт настроек",
        "settings_import" to "Импорт настроек",
        "settings_export_success" to "Настройки экспортированы в Загрузки: %s",
        "settings_export_fail" to "Не удалось экспортировать настройки",
        "settings_export_sub" to "Сохранить архив в Загрузки",
        "settings_import_sub" to "Восстановить из файла .zip",
        "settings_import_success" to "Настройки импортированы. Перезапуск…",
        "settings_import_fail" to "Не удалось импортировать настройки",
        "toast_ping_updated" to "Пинг обновлён: %d/%d",
        "toast_ping_result" to "Пинг: %s ms",
        "toast_ping_source_result" to "Пинг источника: %d/%d",
        "toast_theme_changed" to "Тема изменена: %s",
        "toast_routing_changed" to "Маршрутизация: %s",
        "toast_lan_bypass_on" to "LAN bypass: включен",
        "toast_lan_bypass_off" to "LAN bypass: выключен",
        "toast_vpn_mode" to "Режим VPN",
        "toast_local_proxy_mode" to "Режим локального прокси",
        "toast_lan_sharing_on" to "LAN Sharing: включен",
        "toast_lan_sharing_off" to "LAN Sharing: выключен",
        "toast_mux_on" to "Mux: включен",
        "toast_mux_off" to "Mux: выключен",
        "toast_app_routing" to "Приложения: %s",
        "toast_apps_cleared" to "Список приложений очищен",
        "toast_fake_dns_on" to "Fake DNS: включен",
        "toast_fake_dns_off" to "Fake DNS: выключен",
        "toast_fragment_on" to "Fragment: включен",
        "toast_fragment_off" to "Fragment: выключен",
        "toast_ipv6_on" to "IPv6: включен",
        "toast_ipv6_off" to "IPv6: выключен",
        "toast_autostart_on" to "Автозапуск: включен",
        "toast_autostart_off" to "Автозапуск: выключен",
        "toast_killswitch_on" to "Kill Switch: включен",
        "toast_killswitch_off" to "Kill Switch: выключен",
        "toast_sniffing_on" to "Сниффинг: включен",
        "toast_sniffing_off" to "Сниффинг: выключен",
        "toast_prefer_ipv6_on" to "Предпочитать IPv6: включено",
        "toast_prefer_ipv6_off" to "Предпочитать IPv6: выключено",
        "toast_profile_selected" to "Профиль: %s",
        "toast_profile_created" to "Создан профиль: %s",
        "toast_profile_saved" to "Профиль сохранен",
        "toast_cant_delete_last" to "Нельзя удалить единственный профиль",
        "toast_profile_deleted" to "Удален профиль: %s",
        "toast_invalid_dns_ip" to "Некорректный IP-адрес DNS",
        "toast_log_level" to "Уровень логов: %s",
        "toast_resource_ok" to "Ресурс доступен",
        "toast_resource_fail" to "Ресурс недоступен",
        "toast_tun_stack" to "TUN стек: %s",
        "toast_dns_changed" to "DNS: %s",
        "toast_domain_strategy" to "Domain Strategy: %s",
        "toast_outbound_resolve" to "Outbound Resolve: %s",

        // Log export
        "logs_export_empty" to "Логи пусты",
        "logs_export_fail" to "Не удалось создать файл в Downloads",
        "logs_export_success" to "Логи сохранены в папку Downloads",
        "logs_export_path" to "Логи сохранены в: %s",
        "logs_export_error" to "Ошибка экспорта: %s",

        // Fallback names
        "fallback_subscription" to "Подписка",
        "fallback_source" to "Источник",
        "fallback_unknown" to "Неизвестный",

        // Day plural forms
        "day_1" to "1 день",
        "day_2_4" to "%d дня",
        "day_5_30" to "%d дн.",

        // Settings tab
        "packages_selected" to "%d пакетов",
    )

    private val en = mapOf(
        "title_main" to "Main",
        "title_proxies" to "Proxies",
        "title_settings" to "Settings",
        "title_logs" to "Logs",
        "status_connected" to "VPN is protecting traffic",
        "status_connecting" to "Establishing VPN tunnel",
        "status_reconnecting" to "Connection lost, reconnecting",
        "status_disconnected" to "VPN disconnected",
        "status_no_server" to "No server selected",
        "download" to "Download",
        "upload" to "Upload",
        "quick_best" to "Best Server",
        "quick_share" to "Share Config",
        "quick_vpn_settings" to "VPN Android",
        "quick_tile" to "Add Tile",
        "no_active_config" to "No working configuration selected",
        "conn_params" to "VPN settings, DNS servers, TUN stack, local proxy",
        "rules_params" to "Routing, app routing, Xray core features",
        "appearance_params" to "Theme, click haptics, corner roundness, animations",
        "system_params" to "Logging, auto start, health check, reset",
        "submenu_connection" to "Connection",
        "submenu_rules" to "Rules",
        "submenu_appearance" to "Appearance",
        "submenu_system" to "System",
        "back" to "Back",
        "language" to "Language",
        "lang_system" to "System Default",
        "lang_ru" to "Русский",
        "lang_en" to "English",
        "lang_zh" to "简体中文",
        "theme" to "Theme",
        "tap_impact" to "Click Haptics",
        "tap_impact_none" to "No Haptics (1.00)",
        "tap_impact_light" to "Light (0.95)",
        "tap_impact_medium" to "Medium (0.90)",
        "tap_impact_deep" to "Deep (0.85)",
        "tap_impact_sub" to "UI scale squeeze on press",
        "corner_roundness" to "Corner Style",
        "corner_std" to "Standard (M3)",
        "corner_expr" to "Expressive (M3 Expressive)",
        "corner_std_sub" to "Standard strict Material Design",
        "corner_expr_sub" to "Larger corner radiuses and expressive shapes",
        "effects_anim" to "Effects & Animations",
        "pulse_btn" to "Pulse Button",
        "pulse_btn_sub" to "Pulse animation on central button when connected",
        "glass_bar" to "Glassmorphism",
        "glass_bar_sub" to "Translucent glass effect for bottom tab bar",
        "max_blur" to "Maximum Blur",
        "max_blur_sub" to "Dense matte background without outline (Android 17 style)",
        "logging" to "Logging",
        "log_debug_desc" to "All events, including connection details",
        "log_info_desc" to "Major events and state changes",
        "log_warn_desc" to "Warnings and errors only",
        "log_err_desc" to "Critical errors only",
        "sys_settings" to "System Settings",
        "start_on_boot" to "Start on Boot",
        "start_on_boot_sub" to "Automatically start VPN on device boot",
        "confirm_remove" to "Confirm Delete",
        "confirm_remove_sub" to "Show confirmation before deleting a server",
        "check_servers" to "Health Check",
        "check_resource" to "Test Resource",
        "resource_ok" to "Resource is reachable",
        "resource_fail" to "Resource is unreachable",
        "import_config" to "Add Configuration",
        "import_link" to "Link",
        "import_qr" to "QR Code",
        "import_clipboard" to "Clipboard",
        "clipboard_empty" to "Clipboard is empty!",
        "clipboard_chip" to "From clipboard",
        "clear" to "Clear",
        "unknown_format" to "Unknown format",
        "direct_link" to "Direct link to server",
        "sub_link" to "Subscription link",
        "config_url_label" to "Link or subscription URL",

        // Connections & Routing Details
        "ipv6_tunnel" to "IPv6 in Tunnel",
        "ipv6_tunnel_sub" to "Enable IPv6 routing in virtual interface",
        "prefer_ipv6" to "Prefer IPv6",
        "prefer_ipv6_sub" to "Request IPv6 addresses (AAAA) during domain resolution",
        "lan_bypass" to "Bypass Local Networks",
        "lan_bypass_sub" to "LAN, loopback, and link-local networks bypass VPN",
        "blocking_vpn" to "Block Traffic Without VPN",
        "blocking_vpn_sub" to "Kill Switch — block internet connection if VPN is disconnected or interrupted",
        "dns_servers" to "DNS Servers",
        "local_proxy" to "Local Proxy",
        "vpn_mode" to "VPN Mode",
        "vpn_mode_sub" to "VPN intercepts all device traffic, otherwise local proxy runs",
        "lan_sharing" to "Access from LAN",
        "lan_sharing_sub" to "Allow devices in local network to use your proxy",
        "socks_port_title" to "Local SOCKS Port",
        "socks_port_desc" to "Port for connecting local clients to SOCKS5 proxy",
        "tun_stack_title" to "TUN Stack",
        "routing_rules" to "Routing Rules",
        "routing_bypass_desc" to "Local networks and popular regional ranges go directly",
        "routing_proxy_all_desc" to "All device traffic passes through the selected node",
        "routing_direct_desc" to "Tunnel does not capture traffic, useful for diagnostics",
        "custom_rules" to "Custom Rules",
        "custom_direct_title" to "Direct Connection (DIRECT)",
        "custom_direct_desc" to "Domains or IP addresses that should connect directly without proxy (one per line or comma-separated)",
        "custom_proxy_title" to "Via VPN (PROXY)",
        "custom_proxy_desc" to "Domains or IP addresses that should be forced through the VPN (one per line or comma-separated)",
        "app_profile" to "App Profile",
        "selected_apps" to "Selected Apps",
        "select_btn" to "Select",
        "xray_features" to "Xray Core Features",
        "sniffing" to "Traffic Sniffing",
        "sniffing_desc" to "Sniff HTTP/TLS requests to extract domain name",
        "fragment" to "Fragmentation (Fragment)",
        "fragment_desc" to "Fine fragmenting of TLS handshake to bypass active DPI blocking systems",
        "mux" to "Multiplexing (Mux)",
        "mux_desc" to "Mux — TCP multiplexing to reduce handshake latency and save battery",
        "fake_dns" to "Fake DNS",
        "fake_dns_desc" to "Intercept DNS requests and return virtual IPs for more efficient routing",
        "theme_title" to "Theme",
        "haptics_title" to "Click Haptics",
        "roundness_title" to "Corner Style",
        "effects_title" to "Effects & Animations",
        "dark_theme_style_title" to "Dark Theme Style",
        "display_params_title" to "Display Options",
        "compact_proxy_list" to "Compact proxy list",
        "compact_proxy_list_sub" to "Reduce list item size to save space",
        "show_flags" to "Show country flags",
        "show_flags_sub" to "Display emoji flags for each server",

        // Delete confirmation dialogs
        "delete_profile_confirm_title" to "Delete Profile?",
        "delete_profile_confirm_msg" to "Profile \"{name}\" will be permanently deleted. This action cannot be undone.",
        "delete_config_confirm_title" to "Delete Configuration?",
        "delete_config_confirm_msg" to "Server \"{name}\" will be removed from the list. This action cannot be undone.",
        "delete_source_confirm_title" to "Delete Subscription?",
        "delete_source_confirm_msg" to "Subscription \"{name}\" and all its servers will be permanently deleted.",
        "delete_btn" to "Delete",
        "cancel_btn" to "Cancel",

        // Routing — domain strategy
        "routing_domain_strategy" to "Domain Strategy",
        "routing_domain_strategy_desc" to "Determines how domain names are resolved during routing",
        "domain_strategy_as_is" to "AsIs — no resolve",
        "domain_strategy_as_is_desc" to "Pass domain names directly without DNS resolution (default)",
        "domain_strategy_ip_on_demand" to "IPOnDemand — always resolve",
        "domain_strategy_ip_on_demand_desc" to "Resolve domain to IP on every rule match",
        "domain_strategy_ip_if_non_match" to "IPIfNonMatch — resolve on mismatch",
        "domain_strategy_ip_if_non_match_desc" to "Resolve to IP only if no domain rule matched",

        // Outbound domain resolve method
        "outbound_domain_resolve_method" to "Outbound Resolve Method",
        "outbound_domain_resolve_method_desc" to "How domain names are resolved on the outbound side",
        "outbound_resolve_default" to "Resolve — standard resolution",
        "outbound_resolve_default_desc" to "Standard DNS resolution for outbound connections (default)",
        "outbound_resolve_use_ip" to "UseIP — substitute IP",
        "outbound_resolve_use_ip_desc" to "Replace domain name with its IP address before sending to outbound",
        "outbound_resolve_replace" to "UseIPv4 / UseIPv6 — resolve and replace",
        "outbound_resolve_replace_desc" to "Resolve and replace domain names with IP addresses before outbound",

        // Logs
        "logs_params" to "Event journal, debug output, log export",
        "search_logs" to "Search logs...",
        "logs_export" to "Export",
        "logs_clear" to "Clear",
        "logs_empty" to "No records found.",

        // Dashboard
        "profile_presets" to "Profile Presets",
        "manage_profiles" to "Manage Profiles",
        "quick_utilities" to "Quick Utilities",
        "btn_connected" to "ON",
        "btn_connecting" to "SEARCHING...",
        "btn_reconnecting" to "CANCEL",
        "btn_disconnected" to "START",
        "default_profile" to "Default",
        "current_server" to "Current",
        "no_assigned_server" to "Not assigned (Current)",

        // Proxy tab
        "configurations" to "Configurations",
        "local_configs" to "Local Configurations",
        "test_ping_all" to "Test ping all",
        "refresh_subs" to "Refresh subscriptions",
        "search_nodes" to "Search nodes, countries, protocols",
        "sort_nodes" to "Sort Nodes",
        "no_configs" to "No configurations",
        "nothing_found" to "Nothing found",
        "search_try_again" to "Try changing the query or resetting the filter.",
        "add_config_hint" to "Add a config URL or subscription above.",
        "clear_search" to "Clear search",
        "expand" to "Expand",
        "collapse" to "Collapse",
        "import_placeholder" to "Paste vless://, vmess://, ss://, trojan://",
        "import_error_hint" to "Paste a config or subscription link",
        "ping" to "Ping",
        "refresh" to "Update",
        "rename" to "Name",
        "delete" to "Delete",
        "save" to "Save",
        "cancel" to "Cancel",
        "nodes_count" to "nodes",
        "source" to "Source",
        "name" to "Name",
        "settings" to "Settings",
        "sort_by" to "Sort",
        "filter_by" to "Filter",
        "open_filters" to "Open filters",
        "sort_and_filters" to "Sort & Filters",
        "refresh_short" to "Upd.",
        "add" to "Add",
        "quick_switch_profiles" to "Quick Switch Profiles",
        "new_profile" to "New Profile",
        "add_profile" to "Add Profile",
        "profile_sort_hint" to "Long press the handle to reorder. Tap a profile to edit its settings.",
        "drag_handle" to "Drag",
        "active_label" to "ACTIVE",
        "edit" to "Edit",
        "exit" to "Exit",
        "profile_settings" to "Profile Settings",
        "basic_settings" to "BASIC SETTINGS",
        "profile_name_label" to "Profile Name",
        "profile_name_hint" to "Enter a memorable name for this profile",
        "profile_label" to "Profile",
        "dns_servers_title" to "DNS SERVERS",
        "inherit_dns" to "Inherit from base settings",
        "inherit_dns_sub" to "Global DNS settings from the settings section",
        "last_active_server" to "Last active (auto-save)",
        "dont_change_server" to "Don't change (current server)",
        "use_current_server" to "Use current server",
        "assigned_server" to "Assigned Server",
        "assigned_server_hint" to "Select the server to switch to when this profile is activated.",
        "unsaved_changes_title" to "Unsaved Changes",
        "unsaved_changes_msg" to "Unsaved changes will be lost. Are you sure you want to exit?",
        "vpn_connected" to "VPN connected",
        "raising_tunnel" to "Raising tunnel",
        "reconnecting_msg" to "Reconnecting",
        "vpn_disconnected" to "VPN disconnected",
        "press_to_enter_ip" to "Tap to enter IP",
        "example_dns" to "e.g. 8.8.4.4",
        "example_direct" to "e.g. yandex.ru, 192.168.1.1",
        "example_proxy" to "e.g. google.com, instagram.com",
        "qr_scan_hint" to "Point the camera at the QR code",
        "qr_camera_denied" to "Camera permission not granted",
        "invalid_port" to "Invalid port (1..65535)",
        "empty_fields" to "Name, address, and password cannot be empty",
        "link_copied" to "Link copied!",
        "local_import" to "Local Import",
        "edit_config" to "Editing",
        "close_btn" to "Close",
        "done_btn" to "Done",
        "change_btn" to "Change",
        "remark_label" to "Name (Remarks)",
        "address_label" to "Address (IP/Host)",
        "port_label" to "Port",
        "security_label" to "Security",
        "transport_label" to "Transport (network)",
        "protocol_field" to "Protocol",
        "address_field" to "Address",
        "transport_field" to "Transport",
        "source_field" to "Source",
        "discard_btn" to "Discard",
        "stay_btn" to "Stay",
        "sort_nodes" to "Sort Nodes",
        "sort_by_fmt" to "Sort: %s",
        "filter_by_fmt" to "Filter: %s",
        "open_filters_cd" to "Open filters",
        "nodes_count_fmt" to "%d nodes",
        "save_cd" to "Save",
        "expand_cd" to "Expand",
        "collapse_cd" to "Collapse",
        "settings_cd" to "Settings",
        "delete_cd" to "Delete",
        "add_cd" to "Add Profile",
        "back_cd" to "Back",
        "ping_cd" to "Ping",
        "edit_cd" to "Edit",
        "sources_nodes_fmt" to "%d sources · %d nodes",
        "import_desc" to "Enter proxy server link (vless, vmess, ss, trojan) or subscription URL (http/https):",
        "expired" to "Expired",
        "today" to "Today",
        "until_date" to "until %s",
        "sort_default" to "Default",
        "sort_source" to "Source",
        "sort_ping" to "Ping",
        "sort_name" to "Name",

        // Dark theme styles
        "dark_standard" to "Standard Dark",
        "dark_standard_sub" to "Default Material Design",
        "dark_deep_slate" to "Deep Slate",
        "dark_deep_slate_sub" to "Dark charcoal background (#121212)",
        "dark_midnight_navy" to "Midnight Navy",
        "dark_midnight_navy_sub" to "Elegant midnight navy background (#080C14)",
        "dark_pure_black" to "OLED Pure Black",
        "dark_pure_black_sub" to "Pure black background (#000000) for OLED",

        "dns_system_desc" to "Use system DNS addresses from your Android device",
        "dns_google_desc" to "Secure and fast DNS from Google (8.8.8.8, 8.8.4.4)",
        "dns_cloudflare_desc" to "Private DNS from Cloudflare (1.1.1.1, 1.0.0.1)",
        "dns_adguard_desc" to "Blocks ads, trackers, and phishing sites",
        "tun_stack_title" to "TUN STACK",
        "tun_inherit" to "Inherit from base settings",
        "tun_inherit_sub" to "Global TUN stack from settings section",
        "tun_gvisor_desc" to "gVisor-based stack (default, high stability)",
        "tun_system_desc" to "Android system network stack",
        "tun_mixed_desc" to "Mixed network stack for routing optimization",
        "xray_core_features" to "XRAY CORE FEATURES",
        "option_inherit" to "Inherit",
        "option_enabled" to "Enabled",
        "option_disabled" to "Disabled",
        "xray_sniffing" to "Traffic Sniffing",
        "xray_sniffing_desc" to "Auto-detect domain names for precise filtering and bypass.",
        "xray_fragment_desc" to "Packet fragmentation to bypass DPI by providers.",
        "xray_mux_desc" to "Multiplex TCP connections into one channel to reduce handshake latency.",
        "xray_fake_dns_desc" to "Replace real DNS responses with fake IPs for faster resolution and anonymity.",
        "routing_title" to "TRAFFIC ROUTING",
        "routing_inherit" to "Inherit from base settings",
        "routing_inherit_sub" to "Global routing profile",
        "routing_bypass" to "Bypass LAN, China, and Russia",
        "routing_bypass_sub" to "Local network and regional sites (RU, CN) go direct, rest through proxy.",
        "routing_proxy_all" to "Proxy All",
        "routing_proxy_all_sub" to "All device traffic is routed through the VPN tunnel.",
        "routing_direct" to "Direct Connection",
        "routing_direct_sub" to "All connections go directly bypassing VPN proxy.",
        "app_routing_title" to "APP TUNNELING",
        "app_routing_inherit" to "Inherit from base settings",
        "app_routing_inherit_sub" to "Global app tunneling settings",
        "app_routing_all" to "All apps",
        "app_routing_all_sub" to "Proxy traffic for all installed apps.",
        "app_routing_selected" to "Selected apps only",
        "app_routing_selected_sub" to "VPN tunneling works exclusively for selected apps.",
        "app_routing_bypass" to "Bypass selected apps",
        "app_routing_bypass_sub" to "Selected apps go direct, rest through proxy.",
        "app_routing_select_title" to "Selected apps",
        "app_routing_select_sub" to "%d apps selected",
        "app_routing_select_btn" to "Select",
        "custom_rules_title" to "CUSTOM RULES",
        "custom_rules_inherit_direct" to "Inherit DIRECT rules",
        "custom_rules_inherit_direct_sub" to "Use global direct connection list",
        "custom_rules_own_direct" to "Custom DIRECT rules",
        "custom_rules_own_direct_sub" to "Set custom domains and IPs for direct connection",
        "custom_rules_inherit_proxy" to "Inherit PROXY rules",
        "custom_rules_inherit_proxy_sub" to "Use global proxy list",
        "custom_rules_own_proxy" to "Custom PROXY rules",
        "custom_rules_own_proxy_sub" to "Set custom domains and IPs for proxy",
        "save_changes" to "Save changes",
        "select_server" to "Select Server",
        "dont_change_server_picker" to "Don't change (use current server)",
        "last_active_server_picker" to "Last active (auto-save)",

        // Config details sheet
        "config_details_editing" to "Editing",
        "config_details_close" to "Close",
        "config_details_uuid" to "UUID / Password",
        "config_details_sni" to "SNI",
        "config_details_security" to "Security",
        "config_details_transport" to "Transport (network)",
        "config_details_protocol" to "Protocol",
        "config_details_address" to "Address",
        "config_details_transport_val" to "Transport",
        "config_details_security_val" to "Security",
        "config_details_source" to "Source",
        "config_details_cancel" to "Cancel",
        "config_details_save" to "Save",
        "config_details_done" to "Done",
        "config_details_change" to "Change",
        "config_details_unsaved_title" to "Unsaved Changes",
        "config_details_unsaved_msg" to "You have unsaved changes. Exit without saving?",
        "config_details_exit" to "Exit",
        "config_details_stay" to "Stay",

        // App picker
        "app_picker_title" to "Select Apps",
        "app_picker_count" to "%d selected",
        "app_picker_found" to "Found: %d",
        "app_picker_hide_system" to "Hide system apps",
        "app_picker_search" to "Search by name or package...",
        "app_picker_clear" to "Clear",
        "app_picker_save" to "Save changes",

        // Health check
        "health_url_label" to "Resource URL",
        "health_check_cd" to "Check",

        // ViewModel toasts
        "toast_connection_failure" to "Connection failure",
        "toast_server_selected" to "Server selected: %s",
        "toast_no_configs" to "No available configurations",
        "toast_best_server" to "Best server: %s",
        "toast_adding_subscription" to "Adding subscription...",
        "toast_imported_servers" to "Imported servers: %d",
        "toast_loaded_zero" to "Loaded 0 servers",
        "toast_server_added" to "Server added successfully!",
        "toast_invalid_link" to "Error: Unsupported link format!",
        "toast_updating_subs" to "Updating subscriptions...",
        "toast_updated_servers" to "Updated servers: %d",
        "toast_source_not_found" to "Source not found",
        "toast_updating_sub" to "Updating subscription...",
        "toast_source_renamed" to "Source renamed",
        "toast_deleted_source" to "Deleted: %s",
        "toast_deleted_server" to "Deleted: %s",
        "toast_config_updated" to "Configuration updated",
        "update_latest" to "You're on the latest version",
        "update_available" to "Update available: %s",
        "update_check" to "Check for updates",
        "update_check_fail" to "Couldn't check for updates",
        "update_current_version" to "Version %s",
        "update_whats_new" to "What's new",
        "update_hide" to "Hide",
        "update_download" to "Download update",
        "update_latest" to "You're on the latest version",
        "update_checking" to "Checking…",
        "settings_backup" to "Backup",
        "settings_export" to "Export settings",
        "settings_import" to "Import settings",
        "settings_export_success" to "Settings exported to Downloads: %s",
        "settings_export_fail" to "Failed to export settings",
        "settings_export_sub" to "Save archive to Downloads",
        "settings_import_sub" to "Restore from a .zip file",
        "settings_import_success" to "Settings imported. Restarting…",
        "settings_import_fail" to "Failed to import settings",
        "toast_ping_updated" to "Ping updated: %d/%d",
        "toast_ping_result" to "Ping: %s ms",
        "toast_ping_source_result" to "Source ping: %d/%d",
        "toast_theme_changed" to "Theme changed: %s",
        "toast_routing_changed" to "Routing: %s",
        "toast_lan_bypass_on" to "LAN bypass: on",
        "toast_lan_bypass_off" to "LAN bypass: off",
        "toast_vpn_mode" to "VPN mode",
        "toast_local_proxy_mode" to "Local proxy mode",
        "toast_lan_sharing_on" to "LAN Sharing: on",
        "toast_lan_sharing_off" to "LAN Sharing: off",
        "toast_mux_on" to "Mux: on",
        "toast_mux_off" to "Mux: off",
        "toast_app_routing" to "Apps: %s",
        "toast_apps_cleared" to "App list cleared",
        "toast_fake_dns_on" to "Fake DNS: on",
        "toast_fake_dns_off" to "Fake DNS: off",
        "toast_fragment_on" to "Fragment: on",
        "toast_fragment_off" to "Fragment: off",
        "toast_ipv6_on" to "IPv6: on",
        "toast_ipv6_off" to "IPv6: off",
        "toast_autostart_on" to "Auto start: on",
        "toast_autostart_off" to "Auto start: off",
        "toast_killswitch_on" to "Kill Switch: on",
        "toast_killswitch_off" to "Kill Switch: off",
        "toast_sniffing_on" to "Sniffing: on",
        "toast_sniffing_off" to "Sniffing: off",
        "toast_prefer_ipv6_on" to "Prefer IPv6: on",
        "toast_prefer_ipv6_off" to "Prefer IPv6: off",
        "toast_profile_selected" to "Profile: %s",
        "toast_profile_created" to "Profile created: %s",
        "toast_profile_saved" to "Profile saved",
        "toast_cant_delete_last" to "Cannot delete the only profile",
        "toast_profile_deleted" to "Profile deleted: %s",
        "toast_invalid_dns_ip" to "Invalid DNS IP address",
        "toast_log_level" to "Log level: %s",
        "toast_resource_ok" to "Resource is reachable",
        "toast_resource_fail" to "Resource is unreachable",
        "toast_tun_stack" to "TUN stack: %s",
        "toast_dns_changed" to "DNS: %s",
        "toast_domain_strategy" to "Domain Strategy: %s",
        "toast_outbound_resolve" to "Outbound Resolve: %s",

        // Log export
        "logs_export_empty" to "Logs are empty",
        "logs_export_fail" to "Failed to create file in Downloads",
        "logs_export_success" to "Logs saved to Downloads folder",
        "logs_export_path" to "Logs saved to: %s",
        "logs_export_error" to "Export error: %s",

        // Fallback names
        "fallback_subscription" to "Subscription",
        "fallback_source" to "Source",
        "fallback_unknown" to "Unknown",

        // Day plural forms
        "day_1" to "1 day",
        "day_2_4" to "%d days",
        "day_5_30" to "%d days",

        // Settings tab
        "packages_selected" to "%d packages",
    )

    private val zh = mapOf(
        "title_main" to "主页",
        "title_proxies" to "代理",
        "title_settings" to "设置",
        "title_logs" to "日志",
        "status_connected" to "VPN 正在保护流量",
        "status_connecting" to "正在建立 VPN 隧道",
        "status_reconnecting" to "连接已断开，正在重新连接",
        "status_disconnected" to "VPN 已断开",
        "status_no_server" to "未选择服务器",
        "download" to "下载",
        "upload" to "上传",
        "quick_best" to "最佳服务器",
        "quick_share" to "分享配置",
        "quick_vpn_settings" to "系统 VPN",
        "quick_tile" to "添加瓷贴",
        "no_active_config" to "未选择有效的配置",
        "conn_params" to "VPN 参数、DNS 服务器、TUN 栈、本地代理",
        "rules_params" to "路由、应用代理、Xray 内核功能",
        "appearance_params" to "主题风格、触觉反馈、圆角样式、动画",
        "system_params" to "日志记录、开机自启、服务器检查、重置设置",
        "submenu_connection" to "连接",
        "submenu_rules" to "规则",
        "submenu_appearance" to "外观",
        "submenu_system" to "系统",
        "back" to "返回",
        "language" to "语言",
        "lang_system" to "系统默认",
        "lang_ru" to "Русский",
        "lang_en" to "English",
        "lang_zh" to "简体中文",
        "theme" to "主题",
        "tap_impact" to "按压触觉反馈",
        "tap_impact_none" to "无缩放 (1.00)",
        "tap_impact_light" to "轻微 (0.95)",
        "tap_impact_medium" to "中等 (0.90)",
        "tap_impact_deep" to "强烈 (0.85)",
        "tap_impact_sub" to "按压时界面物理缩放挤压效果",
        "corner_roundness" to "圆角风格",
        "corner_std" to "标准 (M3)",
        "corner_expr" to "丰富 (M3 Expressive)",
        "corner_std_sub" to "标准的 Material Design 严谨设计",
        "corner_expr_sub" to "更大的圆角和更具表现力的形状",
        "effects_anim" to "特效与动画",
        "pulse_btn" to "按钮呼吸灯",
        "pulse_btn_sub" to "连接成功时中心按钮的呼吸动画效果",
        "glass_bar" to "毛玻璃效果",
        "glass_bar_sub" to "底部导航栏的半透明毛玻璃效果",
        "max_blur" to "最大模糊",
        "max_blur_sub" to "无描边的紧密磨砂效果（Android 17 风格，默认开启）",
        "logging" to "日志记录",
        "log_debug_desc" to "所有事件，包括连接的详细信息",
        "log_info_desc" to "主要事件和状态更改",
        "log_warn_desc" to "仅限警告和错误",
        "log_err_desc" to "仅限严重错误",
        "sys_settings" to "系统设置",
        "start_on_boot" to "开机自启",
        "start_on_boot_sub" to "设备开机后自动启动 VPN 连接",
        "confirm_remove" to "删除确认",
        "confirm_remove_sub" to "从列表中删除服务器前询问确认",
        "check_servers" to "服务器连接性检查",
        "check_resource" to "测试资源地址",
        "resource_ok" to "测试成功，资源可达",
        "resource_fail" to "测试失败，资源不可达",
        "import_config" to "添加配置",
        "import_link" to "链接导入",
        "import_qr" to "扫码导入",
        "import_clipboard" to "从剪贴板导入",
        "clipboard_empty" to "剪贴板为空！",
        "clipboard_chip" to "剪贴板",
        "clear" to "清除",
        "unknown_format" to "未知格式",
        "direct_link" to "服务器直连配置链接",
        "sub_link" to "订阅链接",
        "config_url_label" to "链接或订阅 URL",

        // Connections & Routing Details
        "ipv6_tunnel" to "隧道中的 IPv6",
        "ipv6_tunnel_sub" to "在虚拟接口中启用 IPv6 路由",
        "prefer_ipv6" to "首选 IPv6",
        "prefer_ipv6_sub" to "在域名解析期间请求 IPv6 地址 (AAAA)",
        "lan_bypass" to "绕过局域网",
        "lan_bypass_sub" to "局域网、环回和链路本地网络不进入 VPN",
        "blocking_vpn" to "无 VPN 时拦截流量",
        "blocking_vpn_sub" to "Kill Switch — 如果 VPN 断开或中断，则阻止互联网连接",
        "dns_servers" to "DNS 服务器",
        "local_proxy" to "本地代理",
        "vpn_mode" to "VPN 模式",
        "vpn_mode_sub" to "VPN 拦截所有设备流量，否则运行本地代理",
        "lan_sharing" to "允许局域网连接",
        "lan_sharing_sub" to "允许局域网中的其他设备使用您的代理",
        "socks_port_title" to "本地 SOCKS 端口",
        "socks_port_desc" to "连接本地客户端到 SOCKS5 代理的端口",
        "tun_stack_title" to "TUN 堆栈",
        "routing_rules" to "路由规则",
        "routing_bypass_desc" to "本地网络和常用区域 IP 直连",
        "routing_proxy_all_desc" to "设备的所有流量均通过所选节点",
        "routing_direct_desc" to "隧道不获取流量，便于诊断",
        "custom_rules" to "自定义规则",
        "custom_direct_title" to "直连规则 (DIRECT)",
        "custom_direct_desc" to "应直接连接而不通过代理的域名或 IP 地址（每行一个或用逗号分隔）",
        "custom_proxy_title" to "代理规则 (PROXY)",
        "custom_proxy_desc" to "应强制通过 VPN 的域名或 IP 地址（每行一个或用逗号分隔）",
        "app_profile" to "应用代理解析",
        "selected_apps" to "已选应用",
        "select_btn" to "选择",
        "xray_features" to "Xray 内核功能",
        "sniffing" to "流量嗅探",
        "sniffing_desc" to "嗅探 HTTP/TLS 请求以提取域名",
        "fragment" to "分片功能 (Fragment)",
        "fragment_desc" to "微调 TLS 握手分片以绕过 DPI 主动阻断系统",
        "mux" to "多路复用 (Mux)",
        "mux_desc" to "Mux — TCP 多路复用以减少握手延迟并节省电量",
        "fake_dns" to "Fake DNS",
        "fake_dns_desc" to "拦截 DNS 请求并返回虚拟 IP 以进行更高效的路由",
        "theme_title" to "主题",
        "haptics_title" to "触觉反馈",
        "roundness_title" to "圆角样式",
        "effects_title" to "特效与动画",
        "dark_theme_style_title" to "深色主题样式",
        "display_params_title" to "显示选项",
        "compact_proxy_list" to "紧凑代理列表",
        "compact_proxy_list_sub" to "缩小列表项尺寸以节省空间",
        "show_flags" to "显示国旗",
        "show_flags_sub" to "为每个服务器显示国旗",

        // Delete confirmation dialogs
        "delete_profile_confirm_title" to "删除配置文件？",
        "delete_profile_confirm_msg" to "配置文件「{name}」将被永久删除，此操作无法撤销。",
        "delete_config_confirm_title" to "删除配置？",
        "delete_config_confirm_msg" to "服务器「{name}」将从列表中移除，此操作无法撤销。",
        "delete_source_confirm_title" to "删除订阅？",
        "delete_source_confirm_msg" to "订阅「{name}」及其所有服务器将被永久删除。",
        "delete_btn" to "删除",
        "cancel_btn" to "取消",

        // Routing — domain strategy
        "routing_domain_strategy" to "域名策略 (Domain Strategy)",
        "routing_domain_strategy_desc" to "决定路由时如何解析域名",
        "domain_strategy_as_is" to "AsIs — 不解析",
        "domain_strategy_as_is_desc" to "直接传递域名，不进行 DNS 解析（默认）",
        "domain_strategy_ip_on_demand" to "IPOnDemand — 始终解析",
        "domain_strategy_ip_on_demand_desc" to "每次规则匹配时将域名解析为 IP",
        "domain_strategy_ip_if_non_match" to "IPIfNonMatch — 无匹配时解析",
        "domain_strategy_ip_if_non_match_desc" to "仅在没有域名规则匹配时解析为 IP",

        // Outbound domain resolve method
        "outbound_domain_resolve_method" to "出站解析方式",
        "outbound_domain_resolve_method_desc" to "出站连接侧域名的解析方式",
        "outbound_resolve_default" to "Resolve — 标准解析",
        "outbound_resolve_default_desc" to "出站连接的标准 DNS 解析（默认）",
        "outbound_resolve_use_ip" to "UseIP — 替换为 IP",
        "outbound_resolve_use_ip_desc" to "发送到出站之前将域名替换为 IP 地址",
        "outbound_resolve_replace" to "UseIPv4 / UseIPv6 — 解析并替换",
        "outbound_resolve_replace_desc" to "解析并将域名替换为 IP 后发送至出站",

        // Logs
        "logs_params" to "事件日志、调试输出、日志导出",
        "search_logs" to "搜索日志...",
        "logs_export" to "导出",
        "logs_clear" to "清除",
        "logs_empty" to "未找到记录。",

        // Dashboard
        "profile_presets" to "配置预设",
        "manage_profiles" to "管理配置",
        "quick_utilities" to "快捷工具",
        "btn_connected" to "已连接",
        "btn_connecting" to "连接中...",
        "btn_reconnecting" to "取消",
        "btn_disconnected" to "开始",
        "default_profile" to "默认",
        "current_server" to "当前",
        "no_assigned_server" to "未分配（当前）",

        // Proxy tab
        "configurations" to "配置",
        "local_configs" to "本地配置",
        "test_ping_all" to "测试全部延迟",
        "refresh_subs" to "刷新订阅",
        "search_nodes" to "搜索节点、国家、协议",
        "sort_nodes" to "节点排序",
        "no_configs" to "暂无配置",
        "nothing_found" to "未找到相关内容",
        "search_try_again" to "尝试更改搜索词或重置筛选条件。",
        "add_config_hint" to "请在上方添加配置链接或订阅链接。",
        "clear_search" to "清除搜索",
        "expand" to "展开",
        "collapse" to "收起",
        "import_placeholder" to "粘贴 vless://, vmess://, ss://, trojan://",
        "import_error_hint" to "请粘贴配置或订阅链接",
        "ping" to "延迟测试",
        "refresh" to "更新",
        "rename" to "重命名",
        "delete" to "删除",
        "save" to "保存",
        "cancel" to "取消",
        "nodes_count" to "节点",
        "source" to "来源",
        "name" to "名称",
        "settings" to "设置",
        "sort_by" to "排序",
        "filter_by" to "筛选",
        "open_filters" to "打开筛选",
        "sort_and_filters" to "排序和筛选",
        "refresh_short" to "更新",
        "add" to "添加",
        "quick_switch_profiles" to "快速切换配置",
        "new_profile" to "新建配置",
        "add_profile" to "添加配置",
        "profile_sort_hint" to "长按手柄进行排序。点击配置以编辑其设置。",
        "drag_handle" to "拖拽",
        "active_label" to "激活",
        "edit" to "编辑",
        "exit" to "退出",
        "profile_settings" to "配置设置",
        "basic_settings" to "基本设置",
        "profile_name_label" to "配置名称",
        "profile_name_hint" to "为此配置设置一个易记的名称",
        "profile_label" to "配置",
        "dns_servers_title" to "DNS 服务器",
        "inherit_dns" to "从基本设置继承",
        "inherit_dns_sub" to "来自设置部分的全局 DNS 设置",
        "last_active_server" to "上次活跃（自动保存）",
        "dont_change_server" to "不更改（当前服务器）",
        "use_current_server" to "使用当前服务器",
        "assigned_server" to "绑定服务器",
        "assigned_server_hint" to "选择激活此配置时自动切换到的服务器。",
        "unsaved_changes_title" to "未保存的更改",
        "unsaved_changes_msg" to "未保存的更改将丢失。您确定要退出吗？",
        "vpn_connected" to "VPN 已连接",
        "raising_tunnel" to "正在建立隧道",
        "reconnecting_msg" to "正在重新连接",
        "vpn_disconnected" to "VPN 已断开",
        "press_to_enter_ip" to "点击输入 IP",
        "example_dns" to "例如：8.8.4.4",
        "example_direct" to "例如：yandex.ru, 192.168.1.1",
        "example_proxy" to "例如：google.com, instagram.com",
        "qr_scan_hint" to "将摄像头对准二维码",
        "qr_camera_denied" to "未授予相机权限",
        "invalid_port" to "无效端口 (1..65535)",
        "empty_fields" to "名称、地址和密码不能为空",
        "link_copied" to "链接已复制！",
        "local_import" to "本地导入",
        "edit_config" to "编辑",
        "close_btn" to "关闭",
        "done_btn" to "完成",
        "change_btn" to "更改",
        "remark_label" to "名称（备注）",
        "address_label" to "地址（IP/主机）",
        "port_label" to "端口",
        "security_label" to "安全",
        "transport_label" to "传输（网络）",
        "protocol_field" to "协议",
        "address_field" to "地址",
        "transport_field" to "传输",
        "source_field" to "来源",
        "discard_btn" to "放弃",
        "stay_btn" to "留在当前页",
        "sort_nodes" to "节点排序",
        "sort_by_fmt" to "排序：%s",
        "filter_by_fmt" to "筛选：%s",
        "open_filters_cd" to "打开筛选",
        "nodes_count_fmt" to "%d 个节点",
        "save_cd" to "保存",
        "expand_cd" to "展开",
        "collapse_cd" to "收起",
        "settings_cd" to "设置",
        "delete_cd" to "删除",
        "add_cd" to "添加配置",
        "back_cd" to "返回",
        "ping_cd" to "延迟测试",
        "edit_cd" to "编辑",
        "sources_nodes_fmt" to "%d 个来源 · %d 个节点",
        "import_desc" to "请输入代理服务器链接 (vless, vmess, ss, trojan) 或订阅链接 (http/https)：",
        "expired" to "已过期",
        "today" to "今天",
        "until_date" to "至 %s",
        "sort_default" to "默认",
        "sort_source" to "来源",
        "sort_ping" to "延迟",
        "sort_name" to "名称",

        // Dark theme styles
        "dark_standard" to "标准深色",
        "dark_standard_sub" to "默认的 Material Design 风格",
        "dark_deep_slate" to "柔和灰",
        "dark_deep_slate_sub" to "深灰色背景 (#121212)",
        "dark_midnight_navy" to "深邃蓝",
        "dark_midnight_navy_sub" to "优雅的深夜蓝色背景 (#080C14)",
        "dark_pure_black" to "OLED 极黑",
        "dark_pure_black_sub" to "用于 OLED 的纯黑色背景 (#000000)",

        "dns_system_desc" to "使用 Android 设备的系统 DNS 地址",
        "dns_google_desc" to "来自 Google 的安全快速 DNS (8.8.8.8, 8.8.4.4)",
        "dns_cloudflare_desc" to "来自 Cloudflare 的隐私 DNS (1.1.1.1, 1.0.0.1)",
        "dns_adguard_desc" to "拦截广告、追踪器和钓鱼网站",
        "tun_stack_title" to "TUN 堆栈",
        "tun_inherit" to "从基本设置继承",
        "tun_inherit_sub" to "来自设置的全局 TUN 堆栈",
        "tun_gvisor_desc" to "基于 gVisor 的堆栈（默认，高稳定性）",
        "tun_system_desc" to "Android 系统网络堆栈",
        "tun_mixed_desc" to "用于路由优化的混合网络堆栈",
        "xray_core_features" to "XRAY 内核功能",
        "option_inherit" to "继承",
        "option_enabled" to "已启用",
        "option_disabled" to "已禁用",
        "xray_sniffing" to "流量嗅探",
        "xray_sniffing_desc" to "自动检测域名以进行精确过滤和绕过。",
        "xray_fragment_desc" to "数据包分片以绕过提供商的深度包检测 (DPI)。",
        "xray_mux_desc" to "将 TCP 连接多路复用到一条通道以减少握手延迟。",
        "xray_fake_dns_desc" to "用虚假 IP 替换真实 DNS 响应以加快解析速度并提高匿名性。",
        "routing_title" to "流量路由",
        "routing_inherit" to "从基本设置继承",
        "routing_inherit_sub" to "全局路由配置",
        "routing_bypass" to "绕过局域网、中国和俄罗斯",
        "routing_bypass_sub" to "本地网络和区域站点（中俄）直连，其余通过代理。",
        "routing_proxy_all" to "全局代理",
        "routing_proxy_all_sub" to "所有设备流量通过 VPN 隧道。",
        "routing_direct" to "直连",
        "routing_direct_sub" to "所有连接绕过 VPN 代理直连。",
        "app_routing_title" to "应用隧道",
        "app_routing_inherit" to "从基本设置继承",
        "app_routing_inherit_sub" to "全局应用隧道设置",
        "app_routing_all" to "所有应用",
        "app_routing_all_sub" to "代理所有已安装应用的流量。",
        "app_routing_selected" to "仅限选定应用",
        "app_routing_selected_sub" to "VPN 隧道仅适用于选定的应用。",
        "app_routing_bypass" to "绕过选定应用",
        "app_routing_bypass_sub" to "选定应用直连，其余通过代理。",
        "app_routing_select_title" to "已选应用",
        "app_routing_select_sub" to "已选择 %d 个应用",
        "app_routing_select_btn" to "选择",
        "custom_rules_title" to "自定义规则",
        "custom_rules_inherit_direct" to "继承 DIRECT 规则",
        "custom_rules_inherit_direct_sub" to "使用全局直连列表",
        "custom_rules_own_direct" to "自定义 DIRECT 规则",
        "custom_rules_own_direct_sub" to "设置自定义域名和 IP 用于直连",
        "custom_rules_inherit_proxy" to "继承 PROXY 规则",
        "custom_rules_inherit_proxy_sub" to "使用全局代理列表",
        "custom_rules_own_proxy" to "自定义 PROXY 规则",
        "custom_rules_own_proxy_sub" to "设置自定义域名和 IP 用于代理",
        "save_changes" to "保存更改",
        "select_server" to "选择服务器",
        "dont_change_server_picker" to "不更改（使用当前服务器）",
        "last_active_server_picker" to "上次活跃（自动保存）",

        // Config details sheet
        "config_details_editing" to "编辑",
        "config_details_close" to "关闭",
        "config_details_uuid" to "UUID / 密码",
        "config_details_sni" to "SNI",
        "config_details_security" to "安全",
        "config_details_transport" to "传输（网络）",
        "config_details_protocol" to "协议",
        "config_details_address" to "地址",
        "config_details_transport_val" to "传输",
        "config_details_security_val" to "安全",
        "config_details_source" to "来源",
        "config_details_cancel" to "取消",
        "config_details_save" to "保存",
        "config_details_done" to "完成",
        "config_details_change" to "更改",
        "config_details_unsaved_title" to "未保存的更改",
        "config_details_unsaved_msg" to "您有未保存的更改。不保存就退出？",
        "config_details_exit" to "退出",
        "config_details_stay" to "留在当前页",

        // App picker
        "app_picker_title" to "选择应用",
        "app_picker_count" to "已选 %d 个",
        "app_picker_found" to "找到：%d",
        "app_picker_hide_system" to "隐藏系统应用",
        "app_picker_search" to "按名称或包名搜索...",
        "app_picker_clear" to "清除",
        "app_picker_save" to "保存更改",

        // Health check
        "health_url_label" to "资源 URL",
        "health_check_cd" to "检查",

        // ViewModel toasts
        "toast_connection_failure" to "连接失败",
        "toast_server_selected" to "已选择服务器：%s",
        "toast_no_configs" to "没有可用配置",
        "toast_best_server" to "最佳服务器：%s",
        "toast_adding_subscription" to "添加订阅...",
        "toast_imported_servers" to "已导入服务器：%d",
        "toast_loaded_zero" to "已加载 0 台服务器",
        "toast_server_added" to "服务器添加成功！",
        "toast_invalid_link" to "错误：不支持的链接格式！",
        "toast_updating_subs" to "更新订阅...",
        "toast_updated_servers" to "已更新服务器：%d",
        "toast_source_not_found" to "未找到来源",
        "toast_updating_sub" to "更新订阅...",
        "toast_source_renamed" to "来源已重命名",
        "toast_deleted_source" to "已删除：%s",
        "toast_deleted_server" to "已删除：%s",
        "toast_config_updated" to "配置已更新",
        "toast_ping_updated" to "延迟更新：%d/%d",
        "toast_ping_result" to "延迟：%s ms",
        "toast_ping_source_result" to "源延迟：%d/%d",
        "toast_theme_changed" to "主题已更改：%s",
        "toast_routing_changed" to "路由：%s",
        "toast_lan_bypass_on" to "LAN 绕过：开",
        "toast_lan_bypass_off" to "LAN 绕过：关",
        "toast_vpn_mode" to "VPN 模式",
        "toast_local_proxy_mode" to "本地代理模式",
        "toast_lan_sharing_on" to "LAN 共享：开",
        "toast_lan_sharing_off" to "LAN 共享：关",
        "toast_mux_on" to "Mux：开",
        "toast_mux_off" to "Mux：关",
        "toast_app_routing" to "应用：%s",
        "toast_apps_cleared" to "应用列表已清除",
        "toast_fake_dns_on" to "Fake DNS：开",
        "toast_fake_dns_off" to "Fake DNS：关",
        "toast_fragment_on" to "Fragment：开",
        "toast_fragment_off" to "Fragment：关",
        "toast_ipv6_on" to "IPv6：开",
        "toast_ipv6_off" to "IPv6：关",
        "toast_autostart_on" to "开机自启：开",
        "toast_autostart_off" to "开机自启：关",
        "toast_killswitch_on" to "Kill Switch：开",
        "toast_killswitch_off" to "Kill Switch：关",
        "toast_sniffing_on" to "嗅探：开",
        "toast_sniffing_off" to "嗅探：关",
        "toast_prefer_ipv6_on" to "首选 IPv6：开",
        "toast_prefer_ipv6_off" to "首选 IPv6：关",
        "toast_profile_selected" to "配置：%s",
        "toast_profile_created" to "配置已创建：%s",
        "toast_profile_saved" to "配置已保存",
        "toast_cant_delete_last" to "无法删除唯一的配置",
        "update_whats_new" to "更新内容",
        "update_hide" to "收起",
        "update_download" to "下载更新",
        "update_latest" to "已是最新版本",
        "update_checking" to "检查中…",
        "settings_backup" to "备份",
        "settings_export" to "导出设置",
        "settings_import" to "导入设置",
        "settings_export_success" to "设置已导出到下载：%s",
        "settings_export_fail" to "导出设置失败",
        "settings_export_sub" to "保存归档到下载",
        "settings_import_sub" to "从 .zip 文件恢复",
        "settings_import_success" to "设置已导入，正在重启…",
        "settings_import_fail" to "导入设置失败",
        "toast_profile_deleted" to "配置已删除：%s",
        "toast_invalid_dns_ip" to "无效的 DNS IP 地址",
        "toast_log_level" to "日志级别：%s",
        "toast_resource_ok" to "资源可达",
        "toast_resource_fail" to "资源不可达",
        "toast_tun_stack" to "TUN 堆栈：%s",
        "toast_dns_changed" to "DNS：%s",
        "toast_domain_strategy" to "Domain Strategy：%s",
        "toast_outbound_resolve" to "Outbound Resolve：%s",

        // Log export
        "logs_export_empty" to "日志为空",
        "logs_export_fail" to "无法在 Downloads 中创建文件",
        "logs_export_success" to "日志已保存到 Downloads 文件夹",
        "logs_export_path" to "日志已保存到：%s",
        "logs_export_error" to "导出错误：%s",

        // Fallback names
        "fallback_subscription" to "订阅",
        "fallback_source" to "来源",
        "fallback_unknown" to "未知",

        // Day plural forms
        "day_1" to "1 天",
        "day_2_4" to "%d 天",
        "day_5_30" to "%d 天",

        // Settings tab
        "packages_selected" to "%d 个包",
    )

    fun get(key: String, lang: String): String {
        val resolvedLang = if (lang == "system") {
            val sysLang = java.util.Locale.getDefault().language
            when {
                sysLang.startsWith("ru") || sysLang.startsWith("be") || sysLang.startsWith("uk") || sysLang.startsWith("kk") || sysLang.startsWith("ky") -> "ru"
                sysLang.startsWith("zh") -> "zh"
                else -> "en"
            }
        } else {
            lang
        }
        val dict = when (resolvedLang) {
            "en" -> en
            "zh" -> zh
            else -> ru
        }
        return dict[key] ?: ru[key] ?: "??$key??"
    }
}
